"""Codegen the baked FE dictionary as a C source file (Phase 3 / 03-06 D3c).

Reads spfy/data/baked_fe.csv (from spfy/tools/fe_sweep_aggregate.py) and
emits spfy/src/fe/baked_fe.{c,h} -- a sorted, binary-searchable lookup
table for per-word FE output (phoneme sequence, sub-phone states,
voicing, stress, syllable boundaries).

Mirror of baked_pos_to_c.py shape; produces the runtime API documented
in the 03-06 plan's <interfaces> block:

  typedef struct {
      const uint16_t *phonemes;
      size_t          n_phon;
      const uint8_t  *sub_phone_states;
      const uint8_t  *voicing;
      const uint8_t  *stress_per_syl;
      const uint16_t *syl_boundaries;
      size_t          n_syl;
      uint16_t        n_observed;
  } spfy_baked_fe_t;

  int spfy_baked_fe_lookup(const char *word_lower, spfy_baked_fe_t *out);

Wire-up into the FE pipeline is OUT OF SCOPE for plan 03-06; it lands
in plan 03-07+.

Voice-agnostic codegen guard
----------------------------
Every emitted C string literal is checked against a regex that matches
voice substrings (`tom|mara|craig|aimara`, case-insensitive). If any
row of the input CSV contains such a substring, the codegen tool
refuses to emit and exits non-zero with a clear error.

The runtime files (baked_fe.{c,h}) this tool would produce are the
user's responsibility during the manual sweep step; this tool produces
nothing if the input is voice-tainted.

Usage:
  python baked_fe_to_c.py [--csv PATH] [--out-c PATH] [--out-h PATH]
  python baked_fe_to_c.py --self-test  # exercises the voice-agnostic guard

--self-test
-----------
Runs the codegen against a synthetic 1-row CSV containing the literal
word "Tom" (capital T to match the regex). The guard MUST trip; this
script prints "GUARD TRIPPED" on stderr and exits non-zero. The plan's
verify gate checks both signals.
"""
from __future__ import annotations
import argparse
import csv
import io
import os
import re
import sys
from pathlib import Path
from typing import Optional

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CSV = PROJECT_ROOT / "spfy" / "data" / "baked_fe.csv"
DEFAULT_OUT_C = PROJECT_ROOT / "spfy" / "src" / "fe" / "baked_fe.c"
DEFAULT_OUT_H = PROJECT_ROOT / "spfy" / "src" / "fe" / "baked_fe.h"

VOICE_GUARD_RE = re.compile(r"\btom|\bmara|\bcraig|\baimara", re.IGNORECASE)


def voice_guard(value: str, row_idx: int, col: str) -> None:
    """Raise SystemExit if `value` contains a voice substring."""
    if VOICE_GUARD_RE.search(value):
        print(f"GUARD TRIPPED: voice-name substring in CSV row {row_idx} "
              f"column '{col}' value={value!r}", file=sys.stderr)
        raise SystemExit(2)


def parse_int_list(s: str) -> list[int]:
    if not s:
        return []
    return [int(x) for x in s.split("|") if x]


def emit(csv_path: Path, out_c: Path, out_h: Path) -> int:
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")

    rows: list[dict] = []
    with csv_path.open("r", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        for i, row in enumerate(reader, start=1):
            for col, val in row.items():
                if isinstance(val, str):
                    voice_guard(val, i, col or "")
            rows.append(row)

    rows.sort(key=lambda r: r["word"])

    # ---- C file ----
    out_c.parent.mkdir(parents=True, exist_ok=True)
    with out_c.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* AUTO-GENERATED by spfy/tools/baked_fe_to_c.py.\n"
                " * Source: spfy/data/baked_fe.csv (Frida FE sweep).\n"
                " * DO NOT EDIT by hand; rerun the sweep + codegen.\n"
                " *\n"
                " * Phase 3 / 03-06 Deliverable 3c.\n"
                " */\n")
        f.write('#include "baked_fe.h"\n')
        f.write("#include <stdint.h>\n#include <string.h>\n\n")

        # Per-word static arrays.
        for i, r in enumerate(rows):
            phs = parse_int_list(r.get("phoneme_seq", ""))
            sps = parse_int_list(r.get("sub_phone_states", ""))
            voi = parse_int_list(r.get("voicing_per_state", ""))
            stress = parse_int_list(r.get("stress_per_syl", ""))
            bnds = parse_int_list(r.get("syl_boundaries", ""))
            tag = f"w{i}"
            if phs:
                f.write(f"static const uint16_t _phon_{tag}[{len(phs)}] = "
                        f"{{ {','.join(str(x) for x in phs)} }};\n")
            if sps:
                f.write(f"static const uint8_t _sps_{tag}[{len(sps)}] = "
                        f"{{ {','.join(str(x) for x in sps)} }};\n")
            if voi:
                f.write(f"static const uint8_t _voi_{tag}[{len(voi)}] = "
                        f"{{ {','.join(str(x) for x in voi)} }};\n")
            if stress:
                f.write(f"static const uint8_t _str_{tag}[{len(stress)}] = "
                        f"{{ {','.join(str(x) for x in stress)} }};\n")
            if bnds:
                f.write(f"static const uint16_t _bnd_{tag}[{len(bnds)}] = "
                        f"{{ {','.join(str(x) for x in bnds)} }};\n")

        # Word-sorted directory.
        f.write("\ntypedef struct {\n"
                "    const char       *word;\n"
                "    spfy_baked_fe_t   entry;\n"
                "} _spfy_baked_fe_row_t;\n\n")
        f.write(f"#define BAKED_FE_N {len(rows)}\n\n")
        f.write("static const _spfy_baked_fe_row_t _baked_fe_table[BAKED_FE_N] = {\n")
        for i, r in enumerate(rows):
            phs = parse_int_list(r.get("phoneme_seq", ""))
            sps = parse_int_list(r.get("sub_phone_states", ""))
            voi = parse_int_list(r.get("voicing_per_state", ""))
            stress = parse_int_list(r.get("stress_per_syl", ""))
            bnds = parse_int_list(r.get("syl_boundaries", ""))
            tag = f"w{i}"
            word = r["word"].replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    {{ "{word}", {{'
                    f' {("_phon_" + tag) if phs else "NULL"}, {len(phs)},'
                    f' {("_sps_" + tag) if sps else "NULL"},'
                    f' {("_voi_" + tag) if voi else "NULL"},'
                    f' {("_str_" + tag) if stress else "NULL"},'
                    f' {("_bnd_" + tag) if bnds else "NULL"}, {len(stress)},'
                    f' {int(r.get("n_observed") or 0)}'
                    f' }} }},\n')
        f.write("};\n\n")

        f.write("int spfy_baked_fe_lookup(const char *word_lower,\n"
                "                         spfy_baked_fe_t *out) {\n"
                "    int lo = 0, hi = BAKED_FE_N - 1;\n"
                "    while (lo <= hi) {\n"
                "        int mid = (lo + hi) >> 1;\n"
                "        int c = strcmp(_baked_fe_table[mid].word, word_lower);\n"
                "        if (c == 0) { if (out) *out = _baked_fe_table[mid].entry;\n"
                "                      return 1; }\n"
                "        if (c < 0) lo = mid + 1; else hi = mid - 1;\n"
                "    }\n"
                "    return 0;\n"
                "}\n")

    # ---- H file ----
    out_h.parent.mkdir(parents=True, exist_ok=True)
    with out_h.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* AUTO-GENERATED by spfy/tools/baked_fe_to_c.py.\n"
                " * Source: spfy/data/baked_fe.csv (Frida FE sweep).\n"
                " * DO NOT EDIT by hand; rerun the sweep + codegen.\n"
                " *\n"
                " * Phase 3 / 03-06 Deliverable 3c.\n"
                " */\n"
                "#ifndef SPFY_BAKED_FE_H\n"
                "#define SPFY_BAKED_FE_H\n\n"
                "#include <stddef.h>\n"
                "#include <stdint.h>\n\n"
                "typedef struct {\n"
                "    const uint16_t *phonemes;\n"
                "    size_t          n_phon;\n"
                "    const uint8_t  *sub_phone_states;\n"
                "    const uint8_t  *voicing;\n"
                "    const uint8_t  *stress_per_syl;\n"
                "    const uint16_t *syl_boundaries;\n"
                "    size_t          n_syl;\n"
                "    uint16_t        n_observed;\n"
                "} spfy_baked_fe_t;\n\n"
                "int spfy_baked_fe_lookup(const char *word_lower,\n"
                "                         spfy_baked_fe_t *out);\n\n"
                "#endif /* SPFY_BAKED_FE_H */\n")

    print(f"Wrote {len(rows)} entries -> {out_c}")
    print(f"Wrote header                  -> {out_h}")
    return 0


def run_self_test() -> int:
    """Synthesize a 1-row CSV containing the literal word 'Tom' and run
    the codegen. The voice-agnostic guard MUST trip with exit code 2 +
    'GUARD TRIPPED' on stderr. The plan's verify gate looks for both
    signals."""
    import tempfile

    csv_body = io.StringIO()
    w = csv.writer(csv_body)
    w.writerow(["word", "phoneme_seq", "sub_phone_states",
                "voicing_per_state", "stress_per_syl", "syl_boundaries",
                "n_observed", "alt_seq_count"])
    # Deliberately voice-tainted -- guard MUST fire on this row.
    w.writerow(["Tom", "1|2|3", "3|3|3", "1|1|0|1|1|0|1|1|0",
                "1", "0", "1", "1"])

    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        csv_path = td_path / "synthetic_tom.csv"
        csv_path.write_text(csv_body.getvalue(), encoding="utf-8")
        out_c = td_path / "baked_fe.c"
        out_h = td_path / "baked_fe.h"
        try:
            emit(csv_path, out_c, out_h)
        except SystemExit as e:
            # Expected. Re-raise with the same exit code so the shell
            # sees non-zero.
            raise
    # If we reached here without SystemExit, the guard failed.
    print("FAIL: voice-agnostic guard did NOT trigger on Tom-tainted "
          "input", file=sys.stderr)
    return 1


def main() -> int:
    p = argparse.ArgumentParser(
        description="Codegen spfy/src/fe/baked_fe.{c,h} from "
                    "spfy/data/baked_fe.csv (Phase 3 / 03-06 D3c).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out-c", type=Path, default=DEFAULT_OUT_C)
    p.add_argument("--out-h", type=Path, default=DEFAULT_OUT_H)
    p.add_argument("--self-test", action="store_true",
                   help="Run codegen against a synthetic Tom-tainted CSV "
                        "to exercise the voice-agnostic guard. MUST exit "
                        "non-zero with 'GUARD TRIPPED' on stderr.")
    args = p.parse_args()

    if args.self_test:
        return run_self_test()
    return emit(args.csv, args.out_c, args.out_h)


if __name__ == "__main__":
    raise SystemExit(main())
