"""Codegen the baked POS dictionary as a C source file.

Reads spfy/data/baked_pos.csv (from pos_sweep_aggregate.py) and emits
spfy/src/fe/baked_pos.c — a sorted (word, pos_class) lookup table for
binary search at LTS time.

Output schema:

    typedef enum {
        POS_UNKNOWN = 0,
        POS_NOUN, POS_ADJ, POS_VERB, POS_ADV, POS_INTERJ,
        POS_QUANT, POS_NOUN_ADJ, POS_NOUN_VERB,    /* open class */
        POS_DET, POS_AUX, POS_PREP, POS_PRO,
        POS_WH, POS_UNDEF, POS_CONJ,                /* closed class */
        POS_OTHER,
    } spfy_pos_class_t;

    int spfy_baked_pos_lookup(const char *word_lower, spfy_pos_class_t *out);
    int spfy_pos_is_open_class(spfy_pos_class_t p);

Use case at LTS time:

    spfy_pos_class_t pos = POS_UNKNOWN;
    if (spfy_baked_pos_lookup(lowercase_word, &pos)
        && !spfy_pos_is_open_class(pos)) {
        // closed-class: deaccent + suppress lexical stress
        syl_accent[si] = 0;
        syl_stress[si] = 0;
    }

Usage:
  python baked_pos_to_c.py [--csv PATH] [--out PATH]
"""
from __future__ import annotations
import argparse
import csv
import os

DEFAULT_CSV = os.path.expanduser("~/Documents/Speechify/spfy/data/baked_pos.csv")
DEFAULT_OUT = os.path.expanduser("~/Documents/Speechify/spfy/src/fe/baked_pos.c")

POS_ENUM = {
    # Pure open classes
    "noun":           "POS_NOUN",
    "adj":            "POS_ADJ",
    "verb":           "POS_VERB",
    "adv":            "POS_ADV",
    "interj":         "POS_INTERJ",
    "quant":          "POS_QUANT",
    # Combination tags (also open class)
    "noun_adj":       "POS_NOUN_ADJ",
    "noun_verb":      "POS_NOUN_VERB",
    "verb_adj":       "POS_VERB_ADJ",
    "noun_verb_adj":  "POS_NOUN_VERB_ADJ",
    "adj_adv":        "POS_ADJ_ADV",
    # Closed classes
    "det":            "POS_DET",
    "aux":            "POS_AUX",
    "prep":           "POS_PREP",
    "pro":            "POS_PRO",
    "pro2":           "POS_PRO2",
    "wh":             "POS_WH",
    "conj":           "POS_CONJ",
    "dem":            "POS_DEM",        # this/that — demonstrative
    "undef":          "POS_UNDEF",
    # Special / marginal classes
    "there":          "POS_THERE",      # existential there
    "not":            "POS_NOT",
    "postpos":        "POS_POSTPOS",
    "disambigDict":   "POS_DISAMBIG",
    "other":          "POS_OTHER",
}

# Open-class set: words `spfy_pos_is_open_class()` returns TRUE for.
# This is the LITERAL "open-class" set per linguistic theory PLUS the
# context-dependent classes (pro/pro2/wh/undef). Reason: those classes
# accent ~50% of the time depending on context (per MEMORY POS analysis);
# baked_pos can't disambiguate, so we let them through to the FUNC_WORDS
# fallback in spfy_synth, which correctly gates known pronouns + the
# boundary-tone fix re-enables accent on last-syl pronouns. Net: matches
# the previous hand-curated behavior on known words, gains correct
# closed-class gating only for the unambiguous classes (det/aux/prep/
# conj/dem) which have stable engine behavior.
OPEN_ENUMS = {
    # Pure open class (always accent)
    "POS_NOUN", "POS_ADJ", "POS_VERB", "POS_ADV", "POS_INTERJ", "POS_QUANT",
    "POS_NOUN_ADJ", "POS_NOUN_VERB", "POS_VERB_ADJ", "POS_NOUN_VERB_ADJ",
    "POS_ADJ_ADV",
    # Context-dependent / defer to FUNC_WORDS:
    #   POS_PRO, POS_PRO2 — pronouns accent ~50% (boundary tone fix
    #     handles last-syl pronoun via different mechanism)
    #   POS_WH         — wh-words 50% accent ("why" yes, "how" no)
    #   POS_UNDEF      — "one" accents in single-word, varies otherwise
    #   POS_PREP       — most preps never accent (FUNC_WORDS catches),
    #     but verb-particles like "over" in "jumps over" accent. Single-
    #     word sweep can't distinguish; defer to FUNC_WORDS for the
    #     stable ones, accent the rest by default.
    "POS_PRO", "POS_PRO2", "POS_WH", "POS_UNDEF", "POS_PREP",
}


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--csv", default=DEFAULT_CSV)
    p.add_argument("--out", default=DEFAULT_OUT)
    args = p.parse_args()

    rows = []
    with open(args.csv, encoding="utf-8") as fp:
        for r in csv.DictReader(fp):
            w = r["word"].lower().strip()
            if not w: continue
            pos_str = r["pos"].strip()
            enum = POS_ENUM.get(pos_str, "POS_OTHER")
            rows.append((w, enum))
    rows.sort(key=lambda r: r[0])

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fp:
        fp.write('/* AUTO-GENERATED by spfy/tools/baked_pos_to_c.py.\n'
                 ' * Source: spfy/data/baked_pos.csv (Frida POS sweep).\n'
                 ' * DO NOT EDIT by hand; rerun the sweep + codegen. */\n\n')
        fp.write('#include "baked_pos.h"\n')
        fp.write('#include <string.h>\n')
        fp.write('#include <stdlib.h>\n\n')
        fp.write(f'#define BAKED_POS_N {len(rows)}u\n\n')
        fp.write('static const char *const POS_WORDS[BAKED_POS_N] = {\n')
        for w, _ in rows:
            esc = w.replace('"', '\\"').replace('\\', '\\\\')
            fp.write(f'    "{esc}",\n')
        fp.write('};\n\n')
        fp.write('static const unsigned char POS_CLASSES[BAKED_POS_N] = {\n')
        for _, e in rows:
            fp.write(f'    (unsigned char){e},\n')
        fp.write('};\n\n')
        fp.write('int spfy_baked_pos_lookup(const char *w, spfy_pos_class_t *out) {\n')
        fp.write('    if (!w || !*w || !out) return 0;\n')
        fp.write('    int lo = 0, hi = (int)BAKED_POS_N;\n')
        fp.write('    while (lo < hi) {\n')
        fp.write('        int mid = lo + (hi - lo) / 2;\n')
        fp.write('        int cmp = strcmp(w, POS_WORDS[mid]);\n')
        fp.write('        if (cmp == 0) {\n')
        fp.write('            *out = (spfy_pos_class_t)POS_CLASSES[mid];\n')
        fp.write('            return 1;\n')
        fp.write('        }\n')
        fp.write('        if (cmp < 0) hi = mid; else lo = mid + 1;\n')
        fp.write('    }\n')
        fp.write('    *out = POS_UNKNOWN;\n')
        fp.write('    return 0;\n')
        fp.write('}\n\n')
        fp.write('int spfy_pos_is_open_class(spfy_pos_class_t p) {\n')
        fp.write('    switch (p) {\n')
        for enum_name in sorted(OPEN_ENUMS):
            fp.write(f'        case {enum_name}:\n')
        fp.write('            return 1;\n')
        fp.write('        default:\n')
        fp.write('            return 0;\n')
        fp.write('    }\n')
        fp.write('}\n')

    # Also emit the header
    h_path = args.out[:-2] + ".h"
    with open(h_path, "w", encoding="utf-8") as fp:
        fp.write('/* AUTO-GENERATED by spfy/tools/baked_pos_to_c.py. */\n')
        fp.write('#ifndef SPFY_BAKED_POS_H\n#define SPFY_BAKED_POS_H\n\n')
        fp.write('typedef enum {\n')
        fp.write('    POS_UNKNOWN = 0,\n')
        fp.write('    /* Open-class (accent in engine accent rule). */\n')
        fp.write('    POS_NOUN, POS_ADJ, POS_VERB, POS_ADV, POS_INTERJ,\n')
        fp.write('    POS_QUANT, POS_NOUN_ADJ, POS_NOUN_VERB, POS_VERB_ADJ,\n')
        fp.write('    POS_NOUN_VERB_ADJ, POS_ADJ_ADV,\n')
        fp.write('    /* Closed-class (deaccent). */\n')
        fp.write('    POS_DET, POS_AUX, POS_PREP, POS_PRO, POS_PRO2,\n')
        fp.write('    POS_WH, POS_CONJ, POS_DEM, POS_UNDEF,\n')
        fp.write('    /* Special / marginal. */\n')
        fp.write('    POS_THERE, POS_NOT, POS_POSTPOS, POS_DISAMBIG, POS_OTHER,\n')
        fp.write('} spfy_pos_class_t;\n\n')
        fp.write('int spfy_baked_pos_lookup(const char *word_lower, spfy_pos_class_t *out);\n')
        fp.write('int spfy_pos_is_open_class(spfy_pos_class_t p);\n\n')
        fp.write('#endif\n')

    print(f"Wrote {args.out} ({len(rows)} entries)")
    print(f"Wrote {h_path}")


if __name__ == "__main__":
    main()
