#!/usr/bin/env python3
"""cmudict_codegen.py — generate a sorted C lookup table from CMU dict.

Input:  spfy/data/cmudict-0.7b  (CMUdict 0.7b plain text, public domain)
Output: spfy/src/g2p/cmudict_data.c (a static C array consumed by g2p.c)

Format of cmudict-0.7b:
    word PHONEMES
    word(2) PHONEMES   <- alternate pronunciation, skipped
    ...

Output format (intentionally simple — compiler dedups string literals):

    #include "cmudict_data.h"
    const cmudict_entry_t cmudict_entries[] = {
        {"'bout", "B AW1 T"},
        ...
    };
    const size_t cmudict_n_entries = N;

Lookup is binsearch by strcmp on the .word field. We keep only the
primary pronunciation per word (CMU's first listing), since alternates
are noise for our use case.
"""

import sys
import os
import re

PARENS_RE = re.compile(r"\(\d+\)$")  # matches "word(2)"


def parse(path):
    entries = []
    seen = set()
    skipped_alt = 0
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith(";"):
                continue
            # Split first whitespace
            parts = line.split(None, 1)
            if len(parts) != 2:
                continue
            word, phon = parts
            # Skip alternate pronunciations
            if PARENS_RE.search(word):
                skipped_alt += 1
                continue
            if word in seen:
                continue
            seen.add(word)
            entries.append((word, phon))
    return entries, skipped_alt


def escape(s):
    # Words: apostrophes are legal in C strings; no escaping needed for `'`.
    # Backslash and double-quote could exist; defensive escape.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(entries, out_path):
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by spfy/tools/cmudict_codegen.py.\n")
        f.write(" * Source: CMUdict 0.7b (public domain).\n")
        f.write(" * Do not edit by hand — re-run the codegen to regenerate.\n")
        f.write(" */\n\n")
        f.write('#include "cmudict_data.h"\n\n')
        f.write("const cmudict_entry_t cmudict_entries[] = {\n")
        for word, phon in entries:
            f.write(f'    {{"{escape(word)}", "{escape(phon)}"}},\n')
        f.write("};\n\n")
        f.write(f"const size_t cmudict_n_entries = {len(entries)};\n")


def main():
    if len(sys.argv) != 3:
        print("usage: cmudict_codegen.py <cmudict-0.7b> <out.c>",
              file=sys.stderr)
        sys.exit(2)
    in_path, out_path = sys.argv[1], sys.argv[2]
    if not os.path.exists(in_path):
        print(f"input dict not found: {in_path}", file=sys.stderr)
        sys.exit(1)
    entries, skipped_alt = parse(in_path)
    # Sort lexicographically by word for binsearch.
    entries.sort(key=lambda e: e[0])
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    emit(entries, out_path)
    print(f"cmudict_codegen: {len(entries):,} entries -> {out_path}")
    print(f"  ({skipped_alt:,} alternate pronunciations skipped)")


if __name__ == "__main__":
    main()
