#!/usr/bin/env python3
"""cmudict_codegen.py — generate a sorted C lookup table from CMU dict.

Input:  spfy/data/cmudict-0.7b  (CMUdict 0.7b plain text, public domain)
Output: spfy/src/g2p/cmudict_data.c (a static C array consumed by g2p.c)

Format of cmudict-0.7b:
    word PHONEMES
    word(2) PHONEMES   <- alternate pronunciation
    ...

Output format (intentionally simple — compiler dedups string literals):

    #include "cmudict_data.h"
    const cmudict_entry_t cmudict_entries[] = {
        {"'bout", "B AW1 T"},
        ...
    };
    const size_t cmudict_n_entries = N;

Lookup is binsearch by strcmp on the .word field. We keep ONE pronunciation
per word — CMU's primary (first) listing — EXCEPT for the "-day" fix below.

  "-day" fix: SpeechWorks pronounces weekday / -day words with /-deɪ/
  (… D EY), but CMUdict lists the /-di/ (… D IY) form first for the
  weekdays (monday/tuesday/wednesday/thursday/friday/saturday), which made
  the in-house FE say "Mon-dee". When a "-day" word's primary ends in IY and
  an EY alternate exists, we prefer the EY variant — matching the engine
  (verified via spfy_dumpwav --g2p). Single-variant -day words (holiday,
  someday, birthday, sunday, …) already end in EY and are left untouched.
"""

import sys
import os
import re

PARENS_RE = re.compile(r"\(\d+\)$")          # matches "word(2)"
DAY_RE = re.compile(r"day(?:'s|s)?$")         # ...day / ...days / ...day's
ARPA_VOWELS = {
    "AA", "AE", "AH", "AO", "AW", "AY", "EH", "ER", "EY",
    "IH", "IX", "IY", "OW", "OY", "UH", "UW",
}


def base_word(w):
    return PARENS_RE.sub("", w)


def last_vowel(phon):
    """Final ARPAbet vowel of a pronunciation (stress digit stripped), or None."""
    v = None
    for p in phon.split():
        core = p[:-1] if p[-1:].isdigit() else p
        if core in ARPA_VOWELS:
            v = core
    return v


def parse(path):
    variants = {}   # base word -> [phon, ...] in file order
    order = []
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith(";"):
                continue
            parts = line.split(None, 1)
            if len(parts) != 2:
                continue
            word, phon = parts
            bw = base_word(word)
            if bw not in variants:
                variants[bw] = []
                order.append(bw)
            variants[bw].append(phon)

    entries = []
    day_fixed = []
    for bw in order:
        prons = variants[bw]
        chosen = prons[0]                    # CMU's primary listing
        if DAY_RE.search(bw) and last_vowel(chosen) == "IY":
            for alt in prons[1:]:
                if last_vowel(alt) == "EY":
                    chosen = alt
                    day_fixed.append(bw)
                    break
        entries.append((bw, chosen))

    skipped_alt = sum(len(v) - 1 for v in variants.values())
    return entries, skipped_alt, day_fixed


def escape(s):
    # Words: apostrophes are legal in C strings; no escaping needed for `'`.
    # Backslash and double-quote could exist; defensive escape.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(entries, out_path):
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by spfy/tools/cmudict_codegen.py.\n")
        f.write(" * Source: CMUdict 0.7b (public domain).\n")
        f.write(" * Do not edit by hand — re-run the codegen to regenerate.\n")
        f.write(" */\n\n")
        f.write('#include "cmudict_data.h"\n\n')
        f.write("const cmudict_entry_t cmudict_entries[] = {\n")
        for word, phon in entries:
            f.write(f'    {{"{escape(word)}", "{escape(phon)}"}},\n')
        f.write("};\n\n")
        f.write(f"const size_t cmudict_n_entries = {len(entries)};\n")


def main():
    if len(sys.argv) != 3:
        print("usage: cmudict_codegen.py <cmudict-0.7b> <out.c>",
              file=sys.stderr)
        sys.exit(2)
    in_path, out_path = sys.argv[1], sys.argv[2]
    if not os.path.exists(in_path):
        print(f"input dict not found: {in_path}", file=sys.stderr)
        sys.exit(1)
    entries, skipped_alt, day_fixed = parse(in_path)
    # Sort lexicographically by word for binsearch.
    entries.sort(key=lambda e: e[0])
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    emit(entries, out_path)
    print(f"cmudict_codegen: {len(entries):,} entries -> {out_path}")
    print(f"  ({skipped_alt:,} alternate pronunciations skipped)")
    print(f"  (-day EY fix applied to {len(day_fixed)} words: "
          f"{', '.join(day_fixed[:20])}{' …' if len(day_fixed) > 20 else ''})")


if __name__ == "__main__":
    main()
