"""Embed spfy_synth's voice-family + FE asset files into a single C source.

The desktop spfy_synth.exe traditionally takes 7 path arguments
(vin/vdb/vcf/hpclass/vocab.json/fe_tables_a/fe_tables) because the
hpclass + vocab + table directories live outside the user's voice
triplet and are tedious to type. This codegen bakes those four assets
straight into the binary; the runtime extracts them to a tempdir on
startup so the existing path-based loaders need no changes.

Inputs (relative to repo root by default):
    spfy/data/tom_hpclass.bin                 (~170 KB, one blob)
    spfy/build/fe_symbol_table.json           (~30 KB, one blob)
    spfy/data/fe_tables_a/tNNN.bin x 554       (~235 KB, manifest+blob)
    spfy/data/fe_tables/tNNN.bin   x 174       (~600 KB, manifest+blob)

Output: a single .c file with:
    - static const uint8_t blobs (one per asset)
    - static const file_entry_t manifest[] for the two directories
    - void spfy_assets_extract(const char *outdir) — writes everything

Usage:
    python spfy/tools/embed_assets.py \\
        --hpclass spfy/data/tom_hpclass.bin \\
        --vocab   spfy/build/fe_symbol_table.json \\
        --tables-a spfy/data/fe_tables_a \\
        --tables-b spfy/data/fe_tables \\
        --out-c   build/embedded_assets.c
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Tuple


HEADER = """\
/* Auto-generated by spfy/tools/embed_assets.py. DO NOT EDIT.
 *
 * Source assets: hpclass + fe_symbol_table.json + fe_tables_a + fe_tables.
 * Extract via spfy_assets_extract(outdir) — see embedded_assets.h.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#include "embedded_assets.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>

#ifdef _WIN32
#  include <direct.h>
#  define MKDIR(p) _mkdir(p)
#  define PATHSEP '\\\\'
#else
#  define MKDIR(p) mkdir((p), 0755)
#  define PATHSEP '/'
#endif

typedef struct {
    const char *name;        /* e.g. "t000.bin" */
    size_t      offset;
    size_t      size;
} embedded_file_t;

"""


def emit_blob(out: List[str], symbol: str, data: bytes) -> None:
    out.append(f"static const unsigned char {symbol}[{len(data)}] = {{")
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + chunk])
        out.append(f"    {row},")
    out.append("};")
    out.append(f"static const size_t {symbol}_size = {len(data)};")
    out.append("")


def emit_dir(out: List[str], prefix: str, dirpath: Path) -> Tuple[str, str]:
    """Concatenate all *.bin files in dirpath into one blob plus a
    manifest. Returns (blob_symbol, manifest_symbol)."""
    files = sorted(p for p in dirpath.glob("*.bin"))
    if not files:
        print(f"warning: no *.bin in {dirpath}", file=sys.stderr)

    # Compute offsets while accumulating the data
    parts: List[bytes] = []
    entries: List[Tuple[str, int, int]] = []
    offset = 0
    for p in files:
        b = p.read_bytes()
        entries.append((p.name, offset, len(b)))
        parts.append(b)
        offset += len(b)
    blob = b"".join(parts)

    blob_sym = f"{prefix}_blob"
    man_sym = f"{prefix}_manifest"

    emit_blob(out, blob_sym, blob)

    out.append(f"static const embedded_file_t {man_sym}[] = {{")
    for name, off, size in entries:
        out.append(f'    {{ "{name}", {off}, {size} }},')
    out.append("};")
    out.append(f"static const size_t {man_sym}_n = "
               f"sizeof({man_sym}) / sizeof({man_sym}[0]);")
    out.append("")
    return blob_sym, man_sym


def emit_extract_fn(out: List[str],
                    hpc_sym: str, voc_sym: str,
                    ta_blob: str, ta_man: str,
                    tb_blob: str, tb_man: str) -> None:
    out.append(r"""
/* Write a single bytestring to outdir/filename. Creates any required
 * directory as a side effect (best-effort mkdir; ignore EEXIST). */
static int write_file(const char *outdir, const char *filename,
                      const unsigned char *data, size_t n)
{
    char path[1024];
    snprintf(path, sizeof path, "%s%c%s", outdir, PATHSEP, filename);
    FILE *f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "spfy_assets: failed to open %s: ", path);
        perror("");
        return -1;
    }
    if (fwrite(data, 1, n, f) != n) {
        fprintf(stderr, "spfy_assets: short write to %s\n", path);
        fclose(f);
        return -1;
    }
    fclose(f);
    return 0;
}

static int write_dir_files(const char *parent, const char *subdir_name,
                           const unsigned char *blob,
                           const embedded_file_t *manifest, size_t n_files)
{
    char subdir[1024];
    snprintf(subdir, sizeof subdir, "%s%c%s", parent, PATHSEP, subdir_name);
    /* mkdir is best-effort; tolerate EEXIST silently. */
    (void)MKDIR(subdir);
    for (size_t i = 0; i < n_files; ++i) {
        if (write_file(subdir, manifest[i].name,
                       blob + manifest[i].offset,
                       manifest[i].size) != 0) {
            return -1;
        }
    }
    return 0;
}
""")
    out.append("""
int spfy_assets_extract(const char *outdir,
                        spfy_asset_paths_t *out_paths)
{
    (void)MKDIR(outdir);
    if (write_file(outdir, "tom_hpclass.bin",
                   """ + hpc_sym + ", " + hpc_sym + """_size) != 0) return -1;
    if (write_file(outdir, "fe_symbol_table.json",
                   """ + voc_sym + ", " + voc_sym + """_size) != 0) return -1;
    if (write_dir_files(outdir, "fe_tables_a",
                        """ + ta_blob + ", " + ta_man + ", " + ta_man + """_n) != 0)
        return -1;
    if (write_dir_files(outdir, "fe_tables",
                        """ + tb_blob + ", " + tb_man + ", " + tb_man + """_n) != 0)
        return -1;
    if (out_paths) {
        snprintf(out_paths->hpclass, sizeof out_paths->hpclass,
                 "%s%ctom_hpclass.bin", outdir, PATHSEP);
        snprintf(out_paths->vocab,   sizeof out_paths->vocab,
                 "%s%cfe_symbol_table.json", outdir, PATHSEP);
        snprintf(out_paths->tables_a, sizeof out_paths->tables_a,
                 "%s%cfe_tables_a", outdir, PATHSEP);
        snprintf(out_paths->tables_b, sizeof out_paths->tables_b,
                 "%s%cfe_tables", outdir, PATHSEP);
    }
    return 0;
}
""")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--hpclass", required=True, type=Path)
    ap.add_argument("--vocab", required=True, type=Path)
    ap.add_argument("--tables-a", required=True, type=Path)
    ap.add_argument("--tables-b", required=True, type=Path)
    ap.add_argument("--out-c", required=True, type=Path)
    ap.add_argument("--out-h", required=True, type=Path)
    args = ap.parse_args()

    out_h = """\
/* Auto-generated by spfy/tools/embed_assets.py. DO NOT EDIT.
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef SPFY_EMBEDDED_ASSETS_H
#define SPFY_EMBEDDED_ASSETS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Paths written by spfy_assets_extract(). All fixed-size; caller does
 * not need to free anything. */
typedef struct {
    char hpclass [1024];
    char vocab   [1024];
    char tables_a[1024];
    char tables_b[1024];
} spfy_asset_paths_t;

/* Write all four embedded assets (hpclass, vocab, fe_tables_a/*,
 * fe_tables/*) into `outdir`, creating subdirs as needed. Fills
 * `out_paths` (optional, may be NULL) with absolute paths to each.
 * Returns 0 on success, -1 on any I/O error. */
int spfy_assets_extract(const char *outdir,
                        spfy_asset_paths_t *out_paths);

#ifdef __cplusplus
}
#endif

#endif /* SPFY_EMBEDDED_ASSETS_H */
"""
    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_h.write_text(out_h, encoding="utf-8")

    out: List[str] = [HEADER]

    hpc_bytes = args.hpclass.read_bytes()
    emit_blob(out, "hpclass_data", hpc_bytes)
    hpc_sym = "hpclass_data"

    voc_bytes = args.vocab.read_bytes()
    emit_blob(out, "vocab_data", voc_bytes)
    voc_sym = "vocab_data"

    ta_blob, ta_man = emit_dir(out, "tables_a", args.tables_a)
    tb_blob, tb_man = emit_dir(out, "tables_b", args.tables_b)

    emit_extract_fn(out, hpc_sym, voc_sym, ta_blob, ta_man, tb_blob, tb_man)

    args.out_c.parent.mkdir(parents=True, exist_ok=True)
    args.out_c.write_text("\n".join(out), encoding="utf-8")

    total = (len(hpc_bytes) + len(voc_bytes)
             + sum(p.stat().st_size for p in args.tables_a.glob("*.bin"))
             + sum(p.stat().st_size for p in args.tables_b.glob("*.bin")))
    print(f"embed_assets.py: wrote {args.out_c.name} ({total} B embedded)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
