"""Embed spfy_synth's FE asset files into a single C source.

The desktop spfy_synth.exe traditionally takes 7 path arguments
(vin/vdb/vcf/hpclass/vocab.json/fe_tables_a/fe_tables) because the
vocab + table directories live outside the user's voice triplet and
are tedious to type. This codegen bakes those assets straight into the
binary; the runtime extracts them to a tempdir on startup so the
existing path-based loaders need no changes.

The hp_class table is deliberately NOT embedded. It is per-voice, and
baking Tom's copy in made the 5-arg form reject every other voice on
the unit-count check (jill 185475 units vs tom's 169579). It is now
derived from the VIN at load time by spfy_phone_order_hpclass(), which
is byte-exact against the Frida dump for Tom and correct by
construction for the rest. spfy/data/tom_hpclass.bin stays on disk as
the verification reference for `spfy_dump_voice --hpclass`.

Inputs (relative to repo root by default):
    spfy/build/fe_symbol_table.json           (~30 KB, one blob)
    spfy/data/fe_tables_a/tNNN.bin x 554       (~235 KB, manifest+blob)
    spfy/data/fe_tables/tNNN.bin   x 174       (~600 KB, manifest+blob)

Output: a single .c file with:
    - static const uint8_t blobs (one per asset)
    - static const file_entry_t manifest[] for the two directories
    - void spfy_assets_extract(const char *outdir) - writes everything

Usage:
    python spfy/tools/embed_assets.py \\
        --vocab   spfy/build/fe_symbol_table.json \\
        --tables-a spfy/data/fe_tables_a \\
        --tables-b spfy/data/fe_tables \\
        --out-c   build/embedded_assets.c
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import List, Tuple


HEADER = """\
/* Auto-generated by spfy/tools/embed_assets.py. DO NOT EDIT.
 *
 * Source assets: fe_symbol_table.json + fe_tables_a + fe_tables.
 * Extract via spfy_assets_extract(outdir) - see embedded_assets.h.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#include "embedded_assets.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>

#ifdef _WIN32
#  include <direct.h>
#  include <process.h>
#  define MKDIR(p) _mkdir(p)
#  define PATHSEP '\\\\'
#  define GETPID() _getpid()
#else
#  include <unistd.h>
#  define MKDIR(p) mkdir((p), 0755)
#  define PATHSEP '/'
#  define GETPID() getpid()
#endif

/* Written LAST, once every asset is in place. Its presence means a previous
 * run finished extracting, so the whole job can be skipped. */
#define SPFY_ASSETS_STAMP "spfy_assets.complete"

typedef struct {
    const char *name;        /* e.g. "t000.bin" */
    size_t      offset;
    size_t      size;
} embedded_file_t;

"""


def emit_blob(out: List[str], symbol: str, data: bytes,
              emit_size: bool = True) -> None:
    out.append(f"static const unsigned char {symbol}[{len(data)}] = {{")
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + chunk])
        out.append(f"    {row},")
    out.append("};")
    # Single-blob assets (vocab) are copied out by their _size const;
    # directory blobs are sliced via their manifest's per-file offset+length,
    # so their _size const would be dead code (a -Wunused warning). Skip it.
    if emit_size:
        out.append(f"static const size_t {symbol}_size = {len(data)};")
    out.append("")


def emit_dir(out: List[str], prefix: str, dirpath: Path) -> Tuple[str, str]:
    """Concatenate all *.bin files in dirpath into one blob plus a
    manifest. Returns (blob_symbol, manifest_symbol)."""
    files = sorted(p for p in dirpath.glob("*.bin"))
    if not files:
        print(f"warning: no *.bin in {dirpath}", file=sys.stderr)

    # Compute offsets while accumulating the data
    parts: List[bytes] = []
    entries: List[Tuple[str, int, int]] = []
    offset = 0
    for p in files:
        b = p.read_bytes()
        entries.append((p.name, offset, len(b)))
        parts.append(b)
        offset += len(b)
    blob = b"".join(parts)

    blob_sym = f"{prefix}_blob"
    man_sym = f"{prefix}_manifest"

    emit_blob(out, blob_sym, blob, emit_size=False)

    out.append(f"static const embedded_file_t {man_sym}[] = {{")
    for name, off, size in entries:
        out.append(f'    {{ "{name}", {off}, {size} }},')
    out.append("};")
    out.append(f"static const size_t {man_sym}_n = "
               f"sizeof({man_sym}) / sizeof({man_sym}[0]);")
    out.append("")
    return blob_sym, man_sym


def emit_extract_fn(out: List[str],
                    voc_sym: str,
                    ta_blob: str, ta_man: str,
                    tb_blob: str, tb_man: str) -> None:
    out.append(r"""
/* Write a single bytestring to outdir/filename. Creates any required
 * directory as a side effect (best-effort mkdir; ignore EEXIST). */
static int write_file(const char *outdir, const char *filename,
                      const unsigned char *data, size_t n)
{
    char path[1024];
    /* Check the result: an over-long outdir would otherwise silently
     * truncate and write to the WRONG path. (Also what silences GCC's
     * -Wformat-truncation, which fires only on an unused return.) */
    int path_len = snprintf(path, sizeof path, "%s%c%s",
                            outdir, PATHSEP, filename);
    if (path_len < 0 || (size_t)path_len >= sizeof path) {
        fprintf(stderr, "spfy_assets: path too long: %s%c%s\n",
                outdir, PATHSEP, filename);
        return -1;
    }
    /* Already there at the right size? The tempdir name is keyed by the
     * binary's mtime and these blobs are compiled in, so same size means
     * same bytes -- nothing to do. */
    struct stat st;
    if (stat(path, &st) == 0 && (size_t)st.st_size == n) return 0;

    /* Write to a PID-unique temp and rename into place. Several spfy_synth
     * processes routinely extract at once (master_spfy_parity runs 12 workers),
     * and a plain fopen("wb") lets one of them read a half-written asset
     * another is still filling. Rename is atomic enough for that. */
    char tmp[1152];
    int tmp_len = snprintf(tmp, sizeof tmp, "%s.%ld.tmp",
                           path, (long)GETPID());
    if (tmp_len < 0 || (size_t)tmp_len >= sizeof tmp) {
        fprintf(stderr, "spfy_assets: temp path too long for %s\n", path);
        return -1;
    }
    FILE *f = fopen(tmp, "wb");
    if (!f) {
        fprintf(stderr, "spfy_assets: failed to open %s: ", tmp);
        perror("");
        return -1;
    }
    if (fwrite(data, 1, n, f) != n) {
        fprintf(stderr, "spfy_assets: short write to %s\n", tmp);
        fclose(f);
        remove(tmp);
        return -1;
    }
    fclose(f);
    if (rename(tmp, path) != 0) {
        /* Windows rename() refuses an existing target.
         *
         * ⚠ CHECK BEFORE DELETING. An earlier version removed the target and
         * retried, which meant a worker that lost the race DELETED the good
         * file a peer had just placed -- and any third process reading it at
         * that instant failed to load its assets. Symptom: a COLD audit run
         * (fresh binary mtime => fresh tempdir, 12 workers extracting at
         * once) reported dozens of phrases as MISS, and the very next run was
         * clean. Whoever wins the race wins; if their file is the right size
         * it is byte-identical to ours, so just drop our temp. */
        if (stat(path, &st) == 0 && (size_t)st.st_size == n) {
            remove(tmp);
            return 0;
        }
        remove(path);
        if (rename(tmp, path) != 0) {
            remove(tmp);
            if (stat(path, &st) == 0 && (size_t)st.st_size == n) return 0;
            fprintf(stderr, "spfy_assets: failed to place %s\n", path);
            return -1;
        }
    }
    return 0;
}

static int write_dir_files(const char *parent, const char *subdir_name,
                           const unsigned char *blob,
                           const embedded_file_t *manifest, size_t n_files)
{
    char subdir[1024];
    snprintf(subdir, sizeof subdir, "%s%c%s", parent, PATHSEP, subdir_name);
    /* mkdir is best-effort; tolerate EEXIST silently. */
    (void)MKDIR(subdir);
    for (size_t i = 0; i < n_files; ++i) {
        if (write_file(subdir, manifest[i].name,
                       blob + manifest[i].offset,
                       manifest[i].size) != 0) {
            return -1;
        }
    }
    return 0;
}
""")
    out.append("""
int spfy_assets_extract(const char *outdir,
                        spfy_asset_paths_t *out_paths)
{
    /* ⭐ FAST PATH. Extraction writes ~729 small files, and the CLI's 5-arg
     * form calls this on EVERY invocation -- so an audit run that synthesises
     * the corpus was re-writing ~171k files for no reason (measured: the
     * corpus audit went from ~10 s on the legacy 9-arg form, which pointed at
     * on-disk assets, to ~51 s on the 5-arg form).
     *
     * The tempdir is keyed by the binary's mtime, so once a run has finished
     * extracting, the contents are correct for this executable forever. The
     * stamp is written LAST, so seeing it means a complete extraction. */
    char stamp[1024];
    int stamp_len = snprintf(stamp, sizeof stamp, "%s%c%s",
                             outdir, PATHSEP, SPFY_ASSETS_STAMP);
    if (stamp_len < 0 || (size_t)stamp_len >= sizeof stamp) return -1;
    struct stat sst;
    int have_stamp = (stat(stamp, &sst) == 0);

    if (!have_stamp) {
    (void)MKDIR(outdir);
    if (write_file(outdir, "fe_symbol_table.json",
                   """ + voc_sym + ", " + voc_sym + """_size) != 0) return -1;
    if (write_dir_files(outdir, "fe_tables_a",
                        """ + ta_blob + ", " + ta_man + ", " + ta_man + """_n) != 0)
        return -1;
    if (write_dir_files(outdir, "fe_tables",
                        """ + tb_blob + ", " + tb_man + ", " + tb_man + """_n) != 0)
        return -1;
    /* Stamp LAST: its presence is the promise that everything above landed. */
    {
        FILE *sf = fopen(stamp, "wb");
        if (sf) { fputs("ok\\n", sf); fclose(sf); }
    }
    }  /* !have_stamp */
    if (out_paths) {
        snprintf(out_paths->vocab,   sizeof out_paths->vocab,
                 "%s%cfe_symbol_table.json", outdir, PATHSEP);
        snprintf(out_paths->tables_a, sizeof out_paths->tables_a,
                 "%s%cfe_tables_a", outdir, PATHSEP);
        snprintf(out_paths->tables_b, sizeof out_paths->tables_b,
                 "%s%cfe_tables", outdir, PATHSEP);
    }
    return 0;
}
""")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--vocab", required=True, type=Path)
    ap.add_argument("--tables-a", required=True, type=Path)
    ap.add_argument("--tables-b", required=True, type=Path)
    ap.add_argument("--out-c", required=True, type=Path)
    ap.add_argument("--out-h", required=True, type=Path)
    args = ap.parse_args()

    # Content digest over exactly what gets embedded, in a fixed order. This
    # is what makes the extraction directory reusable ACROSS REBUILDS.
    #
    # It used to be keyed on the binary's mtime, which changes on every build
    # even though these tables essentially never do - so every rebuild forced
    # 22 parity workers to re-extract 728 files each, and the audit ran ~22 s
    # against a ~10 s floor. Keyed on content, a rebuild that leaves the FE
    # data alone reuses the existing directory and writes nothing; a rebuild
    # that CHANGES it gets a different directory and cannot read stale files.
    _h = hashlib.sha256()
    _h.update(args.vocab.read_bytes())
    for _d in (args.tables_a, args.tables_b):
        for _p in sorted(_d.glob("*.bin")):
            _h.update(_p.name.encode("utf-8"))
            _h.update(_p.read_bytes())
    digest = _h.hexdigest()[:16]

    out_h = """\
/* Auto-generated by spfy/tools/embed_assets.py. DO NOT EDIT.
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef SPFY_EMBEDDED_ASSETS_H
#define SPFY_EMBEDDED_ASSETS_H

#include <stddef.h>     /* size_t, used by spfy_assets_dir() below */

#ifdef __cplusplus
extern "C" {
#endif

/* Paths written by spfy_assets_extract(). All fixed-size; caller does
 * not need to free anything. */
typedef struct {
    char vocab   [1024];
    char tables_a[1024];
    char tables_b[1024];
} spfy_asset_paths_t;

/* Write the embedded assets (vocab, and the fe_tables_a and fe_tables
 * directories) into `outdir`, creating subdirs as needed. Fills
 * `out_paths` (optional, may be NULL) with absolute paths to each.
 * The hp_class table is NOT among them -- it is per-voice and is derived
 * from the VIN at load time. Returns 0 on success, -1 on any I/O error. */
int spfy_assets_extract(const char *outdir,
                        spfy_asset_paths_t *out_paths);

/* Short hex digest of the embedded content. Callers put it in the extraction
 * directory's NAME, so a directory is reused for as long as the assets are
 * unchanged and is never reused across a change. Do not key that name on the
 * binary's mtime -- these tables outlive thousands of rebuilds. */
#define SPFY_ASSETS_DIGEST "__DIGEST__"

/* Build "<base>/fe_assets_<digest>" into buf. Returns 0 on success, -1 if it
 * would not fit. Both the CLI and the SAPI DLL use this so an installed
 * spfy_synth.exe and spfy_sapi.dll sitting in the same directory share one
 * extracted copy. */
int spfy_assets_dir(const char *base, char *buf, size_t buf_n);

#ifdef __cplusplus
}
#endif

#endif /* SPFY_EMBEDDED_ASSETS_H */
""".replace("__DIGEST__", digest)
    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_h.write_text(out_h, encoding="utf-8")

    out: List[str] = [HEADER]

    voc_bytes = args.vocab.read_bytes()
    emit_blob(out, "vocab_data", voc_bytes)
    voc_sym = "vocab_data"

    ta_blob, ta_man = emit_dir(out, "tables_a", args.tables_a)
    tb_blob, tb_man = emit_dir(out, "tables_b", args.tables_b)

    emit_extract_fn(out, voc_sym, ta_blob, ta_man, tb_blob, tb_man)
    out.append("""
int spfy_assets_dir(const char *base, char *buf, size_t buf_n)
{
    int n;
    if (!base || !buf || buf_n == 0) return -1;
    n = snprintf(buf, buf_n, "%s%cfe_assets_%s",
                 base, PATHSEP, SPFY_ASSETS_DIGEST);
    return (n < 0 || (size_t)n >= buf_n) ? -1 : 0;
}
""")

    args.out_c.parent.mkdir(parents=True, exist_ok=True)
    args.out_c.write_text("\n".join(out), encoding="utf-8")

    total = (len(voc_bytes)
             + sum(p.stat().st_size for p in args.tables_a.glob("*.bin"))
             + sum(p.stat().st_size for p in args.tables_b.glob("*.bin")))
    print(f"embed_assets.py: wrote {args.out_c.name} ({total} B embedded)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
