"""Codegen the engine ARPAbet -> phone-id table as a C source pair.

Reads spfy/data/en_us_engine_phone_ids.csv (built by
spfy/test/oracle/build_phoneid_table.py from prsl_slot + fe_tree
captures) and emits engine_phoneid.{c,h} consumed by fe_parse.c.

The table is a sorted-by-name array of (arpabet, engine_phone_id);
lookup is bsearch. 0xff means "not present in the engine table" -
the caller is expected to fall back (with a stderr warning) to the
voice's VCF phoneset.

Why this exists
---------------
The hosted FE returns ARPAbet strings in tagged output; the engine
internally maps each string to a small integer phone-id used in the
prsl_slot ctx[5] tuple. Tom's VCF uses a different, voice-specific
mapping that disagrees with the engine on common phonemes (e.g.
'dh' is engine_id 10 but VCF id 11). Using the VCF id at the
hosted-FE -> ctx[2] derivation site produced the 1782 ctx mismatches
in the 2026-05-11 master_compare.py audit.

The engine's mapping is loaded from enu.ddl during initStage1 and
is the same for every en-US voice (Tom / Mara / Craig). This codegen
caches it as a C table so we don't have to peek into engine state
at runtime.

Usage:
  python spfy/tools/engine_phoneid_to_c.py \
      [--csv  spfy/data/en_us_engine_phone_ids.csv] \
      [--out-c PATH] [--out-h PATH]
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_CSV = REPO / "spfy" / "data" / "en_us_engine_phone_ids.csv"

HEADER_TEMPLATE = """\
/* engine_phoneid.h — generated by spfy/tools/engine_phoneid_to_c.py.
 * DO NOT EDIT. Re-run codegen if en_us_engine_phone_ids.csv changes.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef SPFY_ENGINE_PHONEID_H
#define SPFY_ENGINE_PHONEID_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Returns the engine's internal phone-id for an ARPAbet symbol, or
 * 0xff if the symbol is not present in the empirical table.
 * Lookup is case-sensitive and bsearch (O(log n)). */
uint8_t spfy_engine_phoneid_lookup(const char *arpabet);

/* Number of distinct ARPAbet symbols in the table. */
extern const uint32_t spfy_engine_phoneid_count;

#ifdef __cplusplus
}}
#endif

#endif /* SPFY_ENGINE_PHONEID_H */
"""

SOURCE_TEMPLATE = """\
/* engine_phoneid.c — generated by spfy/tools/engine_phoneid_to_c.py.
 * DO NOT EDIT. Re-run codegen if en_us_engine_phone_ids.csv changes.
 *
 * Source: en_us_engine_phone_ids.csv ({n_rows} rows, {n_obs} total observations)
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#include "engine_phoneid.h"

#include <stdlib.h>
#include <string.h>

typedef struct {{
    const char *name;
    uint8_t     id;
}} engine_phone_t;

/* Sorted by name (ASCII). bsearch invariant. */
static const engine_phone_t TABLE[] = {{
{rows}
}};

const uint32_t spfy_engine_phoneid_count =
    sizeof(TABLE) / sizeof(TABLE[0]);

static int cmp_name(const void *key, const void *elem) {{
    const char *k = (const char *)key;
    const engine_phone_t *e = (const engine_phone_t *)elem;
    return strcmp(k, e->name);
}}

uint8_t spfy_engine_phoneid_lookup(const char *arpabet) {{
    if (!arpabet) return 0xff;
    const engine_phone_t *r = (const engine_phone_t *)bsearch(
        arpabet, TABLE, spfy_engine_phoneid_count,
        sizeof(TABLE[0]), cmp_name);
    return r ? r->id : 0xff;
}}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--csv", default=str(DEFAULT_CSV))
    ap.add_argument("--out-c", required=True)
    ap.add_argument("--out-h", required=True)
    args = ap.parse_args()

    rows = []
    n_obs = 0
    with open(args.csv, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            name = row["arpabet"]
            pid = int(row["engine_phone_id"])
            n_obs += int(row.get("n_observations", 0))
            if not name.isascii() or any(c == '"' or c == '\\' for c in name):
                print(f"refusing to emit unsafe symbol: {name!r}", file=sys.stderr)
                sys.exit(2)
            rows.append((name, pid))
    rows.sort(key=lambda r: r[0])  # bsearch needs sorted
    body = "\n".join(f'    {{ "{n}", {pid:>3d} }},' for n, pid in rows)

    src = SOURCE_TEMPLATE.format(rows=body, n_rows=len(rows), n_obs=n_obs)
    hdr = HEADER_TEMPLATE

    Path(args.out_c).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_h).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_c).write_text(src, encoding="utf-8")
    Path(args.out_h).write_text(hdr, encoding="utf-8")
    print(f"wrote {args.out_c} ({len(rows)} symbols)")
    print(f"wrote {args.out_h}")


if __name__ == "__main__":
    main()
