"""Convert c:/tmp/fe_dict.jsonl to a generated C lookup file.

Reads the (word -> ARPAbet) JSONL produced by fe_dict_bake.py and emits:
  - spfy/src/fe/baked_dict.h  -- declaration of lookup
  - spfy/src/fe/baked_dict.c  -- sorted-by-spelling table + binary search

The lookup emits vocab IDs that match what stage_spr.c's SAMPA_ARPA table
maps to ARPAbet symbols. NOTE: spfy_dumpwav --help SPR letter conventions
are NOT the same as vocab IDs — e.g. SPR 'a' = vocab 271 = ARPAbet "ae"
(NOT "aa"). This map is authoritative against stage_spr.c, verified against
IRREGULAR_WORDS hand-coded entries.
"""
import json
from pathlib import Path
import os

JSONL_IN  = "c:/tmp/fe_dict.jsonl"
SYM_TABLE = os.path.expanduser("~/Documents/Speechify/spfy/build/fe_symbol_table.json")
H_OUT     = os.path.expanduser("~/Documents/Speechify/spfy/src/fe/baked_dict.h")
C_OUT     = os.path.expanduser("~/Documents/Speechify/spfy/src/fe/baked_dict.c")

# Authoritative ARPAbet -> vocab ID, derived by inverting stage_spr.c's
# SAMPA_ARPA table. This is the same convention IRREGULAR_WORDS uses.
ARPA_TO_VOCAB = {
    # Vowels
    "aa": 259, "ae": 271, "ah": 260, "ao": 278, "aw": 277,
    "ax": 266, "ay": 276, "eh": 258, "er": 264, "ey": 257,
    "ih": 256, "ix": 261, "iy": 255, "ow": 274, "oy": 278,  # oy not separately encoded
    "uh": 273, "uw": 272,
    # Consonants
    "b": 229, "p": 230, "d": 231, "t": 232, "k": 235, "g": 236,
    "f": 240, "v": 239, "th": 238, "dh": 237, "s": 242, "z": 241,
    "sh": 244, "zh": 243, "ch": 246, "jh": 245,
    "hh": 247, "h": 247,
    "m": 248, "n": 249, "ng": 250,
    "r": 251, "l": 252, "y": 253, "w": 254,
    # Allophones / syllabics — map to nearest plain phoneme that the
    # downstream stage_spr.c knows about. The engine emits 'F'=233 for
    # dx and 'L'=265 for el; map those here too so stage_spr.c sees them
    # via its (extended) SAMPA_ARPA table.
    "dx": 233,           # flap T/D (engine vocab 'F'=233)
    "el": 265,           # syllabic l (engine vocab 'L'=265)
    "en": 263,           # syllabic n -> SAMPA 'x' = vocab 263 (engine
                         # encodes /n̩/ as Tom phone_id 14, distinct from
                         # plain 'n' = phone_id 27; verified via prsl_slot
                         # ctx[2]=28 for "important" position 6)
    "pau": None,         # silence — skip
}

def parse_arpabet_token(tok):
    """Strip the optional '(N)' stress marker from a bare ARPAbet symbol."""
    p = tok.find("(")
    return tok[:p] if p >= 0 else tok

def parse_stress(tok):
    """Extract stress digit (0/1/2). Absent marker = 0."""
    p = tok.find("(")
    if p < 0: return 0
    e = tok.find(")", p)
    if e < 0: return 0
    try:
        s = int(tok[p+1:e])
        return s if s in (0, 1, 2) else 0
    except ValueError:
        return 0

def arpa_to_vocab_ids(arpa_str):
    """Convert 'hh(2) eh(2) l(1) ow(1)' -> list of (vocab_id, stress) tuples.
    Returns None if any symbol is unrecognised."""
    out = []
    for tok in arpa_str.split():
        bare = parse_arpabet_token(tok)
        if bare == "pau":
            continue
        vid = ARPA_TO_VOCAB.get(bare)
        if vid is None:
            return None
        out.append((vid, parse_stress(tok)))
    return out

def main():
    entries = []
    rejected = []
    with open(JSONL_IN, encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            arpa = d.get("arpabet", "").strip()
            if not arpa:
                continue
            phons = arpa_to_vocab_ids(arpa)
            if phons is None:
                rejected.append((d["word"], arpa))
                continue
            if not phons:
                continue  # all-pau
            entries.append((d["word"], phons))
    print(f"baked entries: {len(entries)}, rejected: {len(rejected)}")
    if rejected[:5]:
        print("first 5 rejections:")
        for w, a in rejected[:5]:
            print(f"  {w!r} -> {a!r}")

    # Sort by lowercased spelling for binary search; stable to preserve case
    # for tie-breaks (we'll lc on lookup so dups would clash anyway).
    entries.sort(key=lambda e: e[0].lower())
    # Dedupe (case-insensitive); keep first occurrence
    seen = set()
    deduped = []
    for w, phons in entries:
        k = w.lower()
        if k in seen: continue
        seen.add(k)
        deduped.append((w, phons))
    print(f"deduped (case-insensitive): {len(deduped)} entries")

    # Build phoneme pool (concatenated u16) + per-entry (offset, length).
    pool = []
    pool_stress = []
    for w, phons in deduped:
        for vid, stress in phons:
            pool.append(vid)
            pool_stress.append(stress)

    # Write header
    h = []
    h.append("/* AUTO-GENERATED by spfy/tools/fe_dict_to_c.py — DO NOT EDIT. */\n")
    h.append("/* Source: c:/tmp/fe_dict.jsonl (driven by spfy_dumpwav --g2p\n")
    h.append(" * over the registry-A/B word lists). Faithful to the engine\n")
    h.append(" * for words present; OOC words still fall through to heuristic G2P. */\n")
    h.append("#ifndef SPFY_FE_BAKED_DICT_H\n")
    h.append("#define SPFY_FE_BAKED_DICT_H\n\n")
    h.append("#include <stddef.h>\n")
    h.append("#include <stdint.h>\n\n")
    h.append("/* Lookup a word in the baked dictionary.\n")
    h.append(" * Input: lowercase ASCII word + its byte length.\n")
    h.append(" * On hit: *out_phons -> u16 vocab IDs, *out_stress -> u8 stress\n")
    h.append(" *         (0/1/2 ARPAbet stress markers, parallel to out_phons),\n")
    h.append(" *         *out_n is the array length, returns 1.\n")
    h.append(" *         out_stress may be NULL if caller doesn't want stress.\n")
    h.append(" * On miss: returns 0 (out_* untouched). */\n")
    h.append("int spfy_fe_baked_dict_lookup(const char *word_lc, size_t word_len,\n")
    h.append("                              const uint16_t **out_phons,\n")
    h.append("                              const uint8_t  **out_stress,\n")
    h.append("                              size_t *out_n);\n\n")
    h.append("#endif\n")
    Path(H_OUT).write_text("".join(h), encoding="utf-8")
    print(f"wrote {H_OUT}")

    # Write C: sorted spelling array + offset/length arrays + bsearch.
    c = []
    c.append("/* AUTO-GENERATED by spfy/tools/fe_dict_to_c.py — DO NOT EDIT. */\n\n")
    c.append('#include "baked_dict.h"\n\n')
    c.append("#include <stdint.h>\n")
    c.append("#include <string.h>\n\n")
    c.append(f"#define SPFY_FE_BAKED_N      {len(deduped)}\n")
    c.append(f"#define SPFY_FE_BAKED_POOL_N {len(pool)}\n\n")

    # Phoneme pool
    c.append("static const uint16_t POOL[SPFY_FE_BAKED_POOL_N] = {\n")
    for i in range(0, len(pool), 16):
        chunk = ", ".join(str(x) for x in pool[i:i+16])
        c.append(f"    {chunk},\n")
    c.append("};\n\n")

    # Per-phoneme stress (parallel to POOL).
    c.append("static const uint8_t POOL_STRESS[SPFY_FE_BAKED_POOL_N] = {\n")
    for i in range(0, len(pool_stress), 32):
        chunk = ", ".join(str(x) for x in pool_stress[i:i+32])
        c.append(f"    {chunk},\n")
    c.append("};\n\n")

    # Spelling pool (one large NUL-separated buffer)
    sp_buf = bytearray()
    sp_offsets = []
    for w, _ in deduped:
        sp_offsets.append(len(sp_buf))
        sp_buf.extend(w.lower().encode("ascii", "replace"))
        sp_buf.append(0)
    c.append(f"static const char SP_BUF[{len(sp_buf)}] = {{\n")
    for i in range(0, len(sp_buf), 24):
        chunk = ", ".join(str(b) for b in sp_buf[i:i+24])
        c.append(f"    {chunk},\n")
    c.append("};\n\n")

    # Per-entry record: spelling_offset (u32), pool_offset (u32), pool_len (u8)
    c.append("typedef struct { uint32_t sp_off; uint32_t pool_off; uint8_t pool_len; } baked_t;\n")
    c.append("static const baked_t ENT[SPFY_FE_BAKED_N] = {\n")
    pool_off = 0
    for sp_off, (w, phons) in zip(sp_offsets, deduped):
        c.append(f"    {{{sp_off}, {pool_off}, {len(phons)}}},\n")
        pool_off += len(phons)
    c.append("};\n\n")

    # Lookup function
    c.append(
        "int spfy_fe_baked_dict_lookup(const char *word_lc, size_t word_len,\n"
        "                              const uint16_t **out_phons,\n"
        "                              const uint8_t  **out_stress,\n"
        "                              size_t *out_n)\n"
        "{\n"
        "    int lo = 0, hi = SPFY_FE_BAKED_N - 1;\n"
        "    while (lo <= hi) {\n"
        "        int mid = (lo + hi) >> 1;\n"
        "        const char *s = &SP_BUF[ENT[mid].sp_off];\n"
        "        size_t slen = strlen(s);\n"
        "        size_t cmplen = slen < word_len ? slen : word_len;\n"
        "        int c = memcmp(word_lc, s, cmplen);\n"
        "        if (c == 0) {\n"
        "            if (word_len == slen) {\n"
        "                *out_phons = &POOL[ENT[mid].pool_off];\n"
        "                if (out_stress)\n"
        "                    *out_stress = &POOL_STRESS[ENT[mid].pool_off];\n"
        "                *out_n = ENT[mid].pool_len;\n"
        "                return 1;\n"
        "            }\n"
        "            c = (word_len < slen) ? -1 : 1;\n"
        "        }\n"
        "        if (c < 0) hi = mid - 1; else lo = mid + 1;\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
    )
    Path(C_OUT).write_text("".join(c), encoding="utf-8")
    print(f"wrote {C_OUT} ({len(deduped)} entries, pool {len(pool)} u16, "
          f"spelling buf {len(sp_buf)} bytes)")

    # Approximate file size
    approx_kb = (len(pool) * 2 + len(sp_buf) + len(deduped) * 9) / 1024
    print(f"approx code size: {approx_kb:.1f} KB")

if __name__ == "__main__":
    main()
