"""Codegen for engine-derived (word, syl_idx) no-refinement overrides.

Reads c:/tmp/fe_no_refine_overrides.jsonl (built by
c:/tmp/build_no_refine_list.py — walks all
spfy/test/oracle/traces/fe_tree/*.jsonl and aggregates engine's
per-word phoneme inventory).

Each entry is a (word, syl_idx, stress=0) for which engine kept an
unrefined `ih` or `ax` that our R1/R3 rules would have over-refined to
`ix`. We bake them into a sorted binary-search-friendly C table so
apply_phoneme_refinement can skip R1/R3 for that exact (word, syl_idx).

Manual additions:
  - ('to', 0) — engine emits it as 't ax' / 't uw' / 'dx uw' in 8 of 11
    observed patterns (vs 't ix' / 'dx ix' in 3). Net-positive to skip
    refinement even though it's technically ambiguous.

Writes:
  spfy/src/fe_host/fe_no_refine.h  (declarations)
  spfy/src/fe_host/fe_no_refine.c  (sorted table + bsearch lookup)
"""
import os
import json, os, sys

SRC = os.path.expanduser("~/Documents/Speechify/spfy/src/fe_host")
LIST = r"c:/tmp/fe_no_refine_overrides.jsonl"

entries = []  # list of (word, syl_idx)
with open(LIST) as f:
    for ln in f:
        if not ln.strip(): continue
        d = json.loads(ln)
        entries.append((d["word"], int(d["syl_idx"])))

# Manual additions for ambiguous-but-net-positive cases.
manual_extra = [
    ("to", 0),
]
for e in manual_extra:
    if e not in entries:
        entries.append(e)

# Deduplicate and sort
entries = sorted(set(entries))

print(f"emitting {len(entries)} no-refine entries")

hdr = r"""#ifndef SPFY_FE_NO_REFINE_H
#define SPFY_FE_NO_REFINE_H

#include <stddef.h>

/* Lookup: returns 1 if the (word, syl_idx) pair is in the engine-
 * derived no-refinement override table.
 *
 * Generated from engine fe_tree captures (500 phrases) by
 * spfy/tools/no_refine_codegen.py — do not edit by hand. */
int spfy_fe_should_skip_refinement(const char *word, int syl_idx);

#endif /* SPFY_FE_NO_REFINE_H */
"""

c_header = r"""/* AUTOGENERATED — do not edit by hand.
 * Source: c:/tmp/fe_no_refine_overrides.jsonl
 * Generator: spfy/tools/no_refine_codegen.py
 *
 * Engine-derived (word, syl_idx) pairs where SwiTTS Engine emits an
 * unrefined `ih` / `ax` in an unstressed syllable that our R1/R3
 * refinement rules would have over-refined to `ix`. Sorted by
 * (word, syl_idx) for binary-search lookup. */

#include "fe_no_refine.h"
#include <string.h>
#include <stdlib.h>

struct entry { const char *word; int syl_idx; };

static const struct entry TABLE[] = {
"""
lines = [c_header]
for w, si in entries:
    # Escape any potential characters (shouldn't be any but defensive)
    if any(c in w for c in ('"', "\\")):
        raise SystemExit(f"unexpected char in word: {w!r}")
    lines.append(f'    {{ "{w}", {si} }},\n')
lines.append("};\n\n")
lines.append(f"#define TABLE_N ((int)(sizeof(TABLE) / sizeof(TABLE[0])))\n\n")

lines.append(r"""static int cmp(const void *a, const void *b) {
    const struct entry *ea = (const struct entry *)a;
    const struct entry *eb = (const struct entry *)b;
    int c = strcmp(ea->word, eb->word);
    if (c) return c;
    return ea->syl_idx - eb->syl_idx;
}

int spfy_fe_should_skip_refinement(const char *word, int syl_idx) {
    if (!word) return 0;
    struct entry key = { word, syl_idx };
    void *hit = bsearch(&key, TABLE, TABLE_N, sizeof(TABLE[0]), cmp);
    return hit != NULL;
}
""")

with open(os.path.join(SRC, "fe_no_refine.h"), "w", encoding="utf-8") as f:
    f.write(hdr)
with open(os.path.join(SRC, "fe_no_refine.c"), "w", encoding="utf-8") as f:
    f.writelines(lines)
print(f"wrote {SRC}/fe_no_refine.{{h,c}}")
