"""Codegen Tom's voicing table (voice+0x5fc, by hp_class) from an
inner_scorer Frida capture.

Engine inner-scorer (FUN_08e88de0) gates the F0-component computation
on voicing_table[slot_hp_class]: when the value is 0 the entire F0
component is skipped (no miss=5, no delta). spfy_synth.c never loaded
this table, so av->voicing stayed NULL, v_active defaulted to 1, and
we'd add miss=5 on every f0_start==0 cand whose slot's hp_class engine
treats as unvoiced.

Writes:
  spfy/src/usel/tom_voicing.h
  spfy/src/usel/tom_voicing.c
"""
import os
import json, os

TRACE = os.path.expanduser("~/Documents/Speechify/spfy/test/oracle/traces/inner_scorer/text_001.jsonl")
SRC   = os.path.expanduser("~/Documents/Speechify/spfy/src/usel")

with open(TRACE) as f:
    for ln in f:
        d = json.loads(ln)
        if d.get("type") == "join_consts":
            v = d["voice_5fc_per_uid"]["by_hp_class"]
            break
    else:
        raise SystemExit("no join_consts record found")

# Sanity: trim trailing garbage entries (last few are huge ints / metadata).
# Engine's table is 94 hp_classes; values are 0/1. Clamp the tail.
clean = []
for i, x in enumerate(v):
    if x not in (0, 1):
        # Tail garbage — stop here.
        break
    clean.append(x)
print(f"clean entries: {len(clean)} (trimmed {len(v) - len(clean)} tail garbage)")
assert len(clean) >= 64, f"too few clean entries: {len(clean)}"

hdr = r"""#ifndef SPFY_TOM_VOICING_H
#define SPFY_TOM_VOICING_H

#include <stdint.h>

/* Engine's per-hp-class voicing table for Tom (voice+0x5fc).
 *
 * Used by spfy_hp_innerscorer to gate the F0 cost component:
 *   if (voicing_table[hp_class] == 0) -> skip F0 entirely (no miss=5,
 *                                       no delta cost)
 *   else                              -> apply f0_start==0 miss or
 *                                       delta-based cost.
 *
 * Generated by spfy/tools/voicing_codegen.py from a Frida-captured
 * inner_scorer.join_consts.voice_5fc_per_uid.by_hp_class field. */
extern const uint32_t spfy_tom_voicing[];
extern const uint32_t spfy_tom_voicing_n;

#endif
"""

c_lines = [
    "/* AUTOGENERATED by spfy/tools/voicing_codegen.py — do not edit. */\n",
    "#include \"tom_voicing.h\"\n\n",
    "const uint32_t spfy_tom_voicing[] = {\n",
]
# Emit 10 per line
for i in range(0, len(clean), 10):
    row = clean[i:i+10]
    c_lines.append("    " + ", ".join(f"{x}u" for x in row) + ",\n")
c_lines.append("};\n\n")
c_lines.append(f"const uint32_t spfy_tom_voicing_n = {len(clean)}u;\n")

with open(os.path.join(SRC, "tom_voicing.h"), "w", encoding="utf-8") as f:
    f.write(hdr)
with open(os.path.join(SRC, "tom_voicing.c"), "w", encoding="utf-8") as f:
    f.writelines(c_lines)
print(f"wrote {SRC}/tom_voicing.{{h,c}}")
