/* Runtime interface between the interpreter (cpu.c) and the statically
 * recompiled FE functions (recomp_gen_*.c, recomp_tab.c), both generated by
 * spfy/tools/fe_recomp/recomp.py. */
#ifndef RECOMP_H
#define RECOMP_H

#include <stdint.h>

/* RC_OK      the function executed `ret`
 * RC_EXIT    bailed at an instruction boundary; the caller resyncs
 * RC_ABANDON the guest moved past our C frames; unwind, touch nothing */
enum { RC_OK = 0, RC_EXIT = 1, RC_ABANDON = 2 };

int rc_step(uint32_t next);
int rc_run_until(uint32_t ret, uint32_t min_esp);
int rc_dispatch(uint32_t eip);
#define rc_tail rc_dispatch

/* recomp_tab.c: sorted entry VAs, their functions, and the PE identity the
 * translation is valid for. A different image (another FE language) turns
 * recompilation off. */
extern const uint32_t rc_entry_va[];
extern int (*const rc_entry_fn[])(void);
extern const int rc_n_entries;
extern const uint32_t rc_image_base, rc_image_size, rc_image_stamp;

#endif
