#!/usr/bin/env python3
"""Emit a C source that embeds the bytes of a binary file.

Usage: embed_dll.py <input.dll> <output.c> [symbol_prefix]
"""
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    prefix = sys.argv[3] if len(sys.argv) > 3 else "swittsfe_dll"
    data = src.read_bytes()
    lines = [
        "/* Auto-generated by embed_dll.py. DO NOT EDIT. */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "#include <stddef.h>",
        "",
        f"const unsigned char {prefix}_data[] = {{",
    ]
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + chunk])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append(f"const size_t {prefix}_size = sizeof({prefix}_data);")
    lines.append("")
    dst.write_text("\n".join(lines))
    print(f"embed_dll.py: {len(data)} B -> {dst}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
