/*
 * spfy/src/fe_host/fe_parse.c — recursive-descent parser for the
 * tagged-text FE output captured at host/PROTOCOL.md.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Grammar (informal, from PROTOCOL.md):
 *
 *   stream     := "%%" utterance "%%"
 *   utterance  := "#{" body "}"
 *   body       := (pause | word)*
 *   pause      := "pau(p" int ")"
 *   word       := "<" ident "(" int "," int ")" ident "," int "["
 *                 syl_chunk* "]" ">"
 *   syl_chunk  := "." int [ "," accent ] phoneme*
 *   accent     := one of  H* | L* | L+H* | H+L* | L*+H | H*+L
 *                  optionally followed by  ";" boundary
 *   boundary   := L-L% | L-H% | H-L% | H-H% | …
 *   phoneme    := ident "(" "p" int ")"
 *   ident      := [A-Za-z][A-Za-z0-9_]*
 *
 * The parser populates a flat array of `fe_parsed_phoneme_t` with the
 * full prosodic context attached (word POS, syllable stress, accent).
 * `parse_fe_output_into_slots` (in fe_host.c) then flattens this into
 * `spfy_fe_slot_t[]` with the prosody-side fields filled. ctx[5]/sp[5]
 * and CART outputs stay zero until a downstream phoneset crosswalk is
 * wired in.
 */

#include "fe_parse.h"
#include "engine_phoneid.h"   /* generated by spfy/tools/engine_phoneid_to_c.py */
#include "fe_no_refine.h"     /* generated by spfy/tools/no_refine_codegen.py */

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============================================================
 * Tokenizer helpers (cursor-based, never look beyond .end)
 * ============================================================ */

typedef struct {
    const char *p;
    const char *end;
    int err;          /* sticky parse-error flag */
    int err_line_off; /* byte offset where the error occurred */
    const char *err_msg;
} parser_t;

static void p_skip_ws(parser_t *p) {
    while (p->p < p->end && isspace((unsigned char)*p->p)) p->p++;
}

static int p_peek(parser_t *p) {
    return (p->p < p->end) ? (unsigned char)*p->p : -1;
}

static int p_match_lit(parser_t *p, const char *lit) {
    p_skip_ws(p);
    size_t n = strlen(lit);
    if ((size_t)(p->end - p->p) < n) return 0;
    if (memcmp(p->p, lit, n) != 0) return 0;
    p->p += n;
    return 1;
}

static int p_expect_lit(parser_t *p, const char *lit) {
    if (!p_match_lit(p, lit)) {
        if (!p->err) {
            p->err = 1;
            p->err_msg = lit;
            p->err_line_off = (int)(p->p - (p->end - (p->end - p->p)));
        }
        return 0;
    }
    return 1;
}

static int p_parse_int(parser_t *p, int *out) {
    p_skip_ws(p);
    if (p->p >= p->end || !isdigit((unsigned char)*p->p)) return 0;
    int v = 0;
    while (p->p < p->end && isdigit((unsigned char)*p->p)) {
        v = v * 10 + (*p->p - '0');
        p->p++;
    }
    *out = v;
    return 1;
}

/* Identifier: starts with letter/underscore, continues with
 * alphanumeric/underscore. The hosted FE also emits apostrophes
 * inside word names (e.g. `o'clock`, `don't`, `it's`); accept those
 * as continuation chars so we don't bail mid-word.
 * Writes up to buf_sz-1 chars + NUL. Returns length copied. */
static int p_parse_ident(parser_t *p, char *buf, size_t buf_sz) {
    p_skip_ws(p);
    if (p->p >= p->end) return 0;
    int c = (unsigned char)*p->p;
    /* A byte >= 0x80 is an accented Latin-1 letter in a word name -- the
     * FE emits fr-CA/es-MX words like "días", "niño", "être" with their
     * accents intact. isalpha()/isalnum() reject those in the C locale, so
     * the tokeniser used to stop mid-word (leaving the following `(` of the
     * `(offset,len)` tag unexpected -> "error at offset N: (") and drop the
     * whole phrase. Accept high bytes as word-name letters. ASCII (en-US)
     * is unaffected. */
    if (!(isalpha(c) || c == '_' || c >= 0x80)) return 0;
    size_t n = 0;
    while (p->p < p->end) {
        c = (unsigned char)*p->p;
        if (!(isalnum(c) || c == '_' || c == '\'' || c >= 0x80)) break;
        if (n + 1 < buf_sz) buf[n] = (char)c;
        n++;
        p->p++;
    }
    if (buf_sz > 0) buf[(n < buf_sz) ? n : buf_sz - 1] = '\0';
    return (int)n;
}

/* Phoneme symbol: as p_parse_ident, plus '~'.
 *
 * fr-CA marks nasal vowels with a trailing tilde -- its phone set is
 * `... a~ e eu ... oe oe~ ox o~ ...`. Without '~' as a continuation char
 * the parser stops mid-symbol on `o~(p100)` and then fails looking for
 * '('. Kept separate from p_parse_ident so widening the phoneme charset
 * cannot change how WORD names are tokenised. en-US and es-MX symbols
 * are pure alnum and so are unaffected. */
static int p_parse_phone_ident(parser_t *p, char *buf, size_t buf_sz) {
    p_skip_ws(p);
    if (p->p >= p->end) return 0;
    int c = (unsigned char)*p->p;
    if (!(isalpha(c) || c == '_')) return 0;
    size_t n = 0;
    while (p->p < p->end) {
        c = (unsigned char)*p->p;
        if (!(isalnum(c) || c == '_' || c == '\'' || c == '~')) break;
        if (n + 1 < buf_sz) buf[n] = (char)c;
        n++;
        p->p++;
    }
    if (buf_sz > 0) buf[(n < buf_sz) ? n : buf_sz - 1] = '\0';
    return (int)n;
}

/* Accent tokens are not bare identifiers — they contain `*`, `+`, `;`,
 * `-`, `%`. Parse until we hit a non-accent char (whitespace, ` `,
 * letter prefix of phoneme, etc.). Specifically: read while the char
 * is one of [A-Za-z0-9*+;-%]. The token typically looks like:
 *   H*           pitch accent only
 *   L*           pitch accent only
 *   H*;L-L%      pitch accent + phrase + boundary
 *   L+H*         compound pitch accent
 */
static int p_parse_accent(parser_t *p, char *buf, size_t buf_sz) {
    p_skip_ws(p);
    size_t n = 0;
    while (p->p < p->end) {
        int c = (unsigned char)*p->p;
        if (isalnum(c) || c == '*' || c == '+' || c == ';' ||
            c == '-' || c == '%') {
            if (n + 1 < buf_sz) buf[n] = (char)c;
            n++; p->p++;
        } else break;
    }
    if (buf_sz > 0) buf[(n < buf_sz) ? n : buf_sz - 1] = '\0';
    return (int)n;
}

/* ============================================================
 * Grammar productions
 * ============================================================ */

static int parse_pau(parser_t *p, fe_parsed_t *out, int post_word) {
    /* "pau(p" int ")" — already saw "pau"; consume "(p", digits, ")".
     * FE also emits "pau(p?d)" ("default duration") when it hasn't picked
     * a concrete value (e.g. trailing phrase-boundary pause with plain-text
     * input). Treat `?d` as 0 rather than a parse error. */
    if (!p_expect_lit(p, "(")) return 0;
    if (!p_expect_lit(p, "p")) return 0;
    int dur = 0;
    if (p_peek(p) == '?') {
        p->p++;
        if (p_peek(p) == 'd') p->p++;
        dur = 0;
    } else if (!p_parse_int(p, &dur)) {
        p->err = 1; p->err_msg = "pau duration"; return 0;
    }
    if (!p_expect_lit(p, ")")) return 0;
    if (out) {
        if (out->n_words == 0 && !post_word) {
            out->pause_before_ms = dur;
        } else if (post_word) {
            out->pause_after_ms = dur;
        } else {
            /* Inter-word pause — attach to the previous word's trailing
             * pause field. */
            out->words[out->n_words - 1].pause_after_ms = dur;
        }
    }
    return 1;
}

static int ensure_word_cap(fe_parsed_t *out) {
    if (out->n_words >= out->words_cap) {
        int nc = out->words_cap ? out->words_cap * 2 : 8;
        fe_parsed_word_t *p = (fe_parsed_word_t *)
            realloc(out->words, (size_t)nc * sizeof(*p));
        if (!p) return 0;
        out->words = p; out->words_cap = nc;
        /* zero-init the new tail */
        memset(out->words + out->n_words, 0,
               (size_t)(nc - out->n_words) * sizeof(*p));
    }
    return 1;
}

static void apply_phoneme_refinement(fe_parsed_t *out);   /* defined below */

/* fr-CA liaison stress inheritance. When a word arrives with bare leading
 * phonemes (no `.N`), those phones continue the PREVIOUS word's final
 * syllable, so they should inherit its stress rather than default to 0.
 * Off by default (en-US/es-MX never emit bare-leading words); fe_host turns
 * it on only for the fr-CA image. See fe_parse_set_liaison_inherit. */
static int s_liaison_inherit_stress = 0;

static int ensure_phoneme_cap(fe_parsed_word_t *w) {
    if (w->n_phonemes >= w->phonemes_cap) {
        int nc = w->phonemes_cap ? w->phonemes_cap * 2 : 16;
        fe_parsed_phoneme_t *p = (fe_parsed_phoneme_t *)
            realloc(w->phonemes, (size_t)nc * sizeof(*p));
        if (!p) return 0;
        w->phonemes = p; w->phonemes_cap = nc;
        memset(w->phonemes + w->n_phonemes, 0,
               (size_t)(nc - w->n_phonemes) * sizeof(*p));
    }
    return 1;
}

static int parse_phoneme(parser_t *p, fe_parsed_word_t *w,
                         int cur_stress, const char *cur_accent) {
    char name[16];
    if (p_parse_phone_ident(p, name, sizeof(name)) <= 0) return 0;
    if (!p_expect_lit(p, "(")) return 0;
    if (!p_expect_lit(p, "p")) return 0;
    int dur = 0;
    if (!p_parse_int(p, &dur)) { p->err = 1; p->err_msg = "phn duration"; return 0; }
    if (!p_expect_lit(p, ")")) return 0;

    if (!ensure_phoneme_cap(w)) { p->err = 1; p->err_msg = "oom"; return 0; }
    fe_parsed_phoneme_t *ph = &w->phonemes[w->n_phonemes++];
    strncpy(ph->arpabet, name, sizeof(ph->arpabet) - 1);
    ph->arpabet[sizeof(ph->arpabet) - 1] = '\0';
    ph->duration = dur;
    ph->syl_stress = (int8_t)cur_stress;
    strncpy(ph->accent, cur_accent ? cur_accent : "",
            sizeof(ph->accent) - 1);
    ph->accent[sizeof(ph->accent) - 1] = '\0';
    ph->syl_index = w->n_syllables - 1;
    return 1;
}

static int parse_word_body(parser_t *p, fe_parsed_word_t *w,
                           int prev_last_stress) {
    /* Inside the [ ... ]. Each syllable begins with `.X` (X = 0/1),
     * optionally `,accent`. Then one or more phonemes. Multiple
     * syllables can appear back-to-back. */
    int cur_stress = 0;
    char cur_accent[24] = "";

    p_skip_ws(p);
    while (p->p < p->end && p_peek(p) != ']') {
        if (p_peek(p) == '.') {
            p->p++; /* consume '.' */
            int st;
            if (!p_parse_int(p, &st)) {
                p->err = 1; p->err_msg = "syl stress digit"; return 0;
            }
            cur_stress = st;
            cur_accent[0] = '\0';
            p_skip_ws(p);
            /* Accent introducer is comma for pitch-accented syllables
             * (.1,H*) and semicolon for boundary-tone-only syllables
             * on otherwise unstressed positions (.0;L-L%, observed
             * on word-final unstressed syllables of pronouns like
             * "it"). Both produce a ToBI string in cur_accent. */
            if (p_peek(p) == ',' || p_peek(p) == ';') {
                p->p++;
                if (p_parse_accent(p, cur_accent, sizeof(cur_accent)) <= 0) {
                    p->err = 1; p->err_msg = "accent"; return 0;
                }
            }
            w->n_syllables++;
            continue;
        }
        /* Liaison / enchainement (fr-CA): a word's phone list can begin
         * WITHOUT a leading `.N` marker, because its first phone belongs
         * to the syllable whose nucleus sits in the PREVIOUS word --
         *   <un (0,2) art,0 [.0 oe~ .0 n ]> <essai [e .1,H* s E ]>
         *   <nord ... [.1 n c .0 r ]>       <et [e ]>
         * Open an implicit unstressed syllable so the phone lands at
         * syl_index 0 rather than -1; a negative index collapsed the slot
         * tree to n_halfphone==0, which surfaced as a bare "format error".
         * Cannot fire for en-US or es-MX -- every word in those phonesets
         * opens with an explicit `.N`. */
        if (w->n_syllables == 0) {
            w->n_syllables++;
            /* These bare leading phones belong to the PREVIOUS word's final
             * syllable (e.g. "J'aime" = <j' [.1 Z]> <aime [E m]> is one
             * stressed syllable /ZEm/). Inherit that syllable's stress so
             * sylType matches the engine instead of collapsing to the
             * unstressed default. fr-CA only; en-US/es-MX never reach here. */
            if (s_liaison_inherit_stress && cur_stress == 0)
                cur_stress = prev_last_stress;
        }
        if (!parse_phoneme(p, w, cur_stress, cur_accent)) return 0;
        p_skip_ws(p);
    }
    return 1;
}

static int parse_word(parser_t *p, fe_parsed_t *out) {
    /* "<" already consumed by caller. */
    fe_parsed_word_t *w = NULL;
    if (!ensure_word_cap(out)) { p->err = 1; p->err_msg = "oom"; return 0; }
    w = &out->words[out->n_words++];
    memset(w, 0, sizeof(*w));

    if (p_parse_ident(p, w->text, sizeof(w->text)) <= 0) {
        p->err = 1; p->err_msg = "word name"; return 0;
    }
    if (!p_expect_lit(p, "(")) return 0;
    /* Numbers and other text expanded by the FE produce auxiliary
     * words (e.g. "123" -> wun hundred twenty three) where only the
     * first word carries the source-text span; the rest get "()".
     * Accept an empty span as (0, 0). */
    p_skip_ws(p);
    if (p_peek(p) == ')') {
        w->char_start = 0;
        w->char_len = 0;
    } else {
        /* The FE emits `?d` (its "default/unspecified" marker) instead of
         * a numeric char_start when the DLL didn't compute one — happens
         * with the plain-text feedConfigA path used by both fe_host.c and
         * fe_host_emu.c. Treat it as 0 rather than a parse error; slot
         * construction doesn't need char_start for the synth path, only
         * downstream diagnostics do. */
        if (p_peek(p) == '?') {
            p->p++;  /* consume '?' */
            if (p_peek(p) == 'd') p->p++;
            w->char_start = 0;
        } else if (!p_parse_int(p, &w->char_start)) {
            p->err = 1; p->err_msg = "char_start"; return 0;
        }
        if (!p_expect_lit(p, ",")) return 0;
        if (!p_parse_int(p, &w->char_len)) {
            p->err = 1; p->err_msg = "char_len"; return 0;
        }
    }
    if (!p_expect_lit(p, ")")) return 0;
    if (p_parse_ident(p, w->pos, sizeof(w->pos)) <= 0) {
        p->err = 1; p->err_msg = "pos"; return 0;
    }
    if (!p_expect_lit(p, ",")) return 0;
    if (!p_parse_int(p, &w->stress_level)) {
        p->err = 1; p->err_msg = "stress_level"; return 0;
    }
    /* Optional SSML/Balabolka prosody trailers ",p=N" and/or ",r=M".
     * Either may appear (or both, in either order); both omitted in the
     * common plain-text path so the audit round-trip stays clean.
     * The parser is liberal: unknown trailing ",key=value" pairs are
     * accepted and skipped so the format can grow without breaking
     * older readers. */
    p_skip_ws(p);
    while (p_peek(p) == ',') {
        ++p->p;                       /* consume the ',' */
        p_skip_ws(p);
        char key[8] = {0};
        int  ki = 0;
        while (p->p < p->end && ki + 1 < (int)sizeof(key)) {
            int c = (unsigned char)*p->p;
            if (!(isalpha(c) || c == '_')) break;
            key[ki++] = (char)c;
            ++p->p;
        }
        key[ki] = '\0';
        if (p_peek(p) != '=') break;  /* malformed — bail to "[" expect */
        ++p->p;                       /* consume '=' */
        p_skip_ws(p);
        /* Signed integer parse (p_parse_int handles unsigned only). */
        int sign = 1;
        if (p_peek(p) == '-') { sign = -1; ++p->p; }
        else if (p_peek(p) == '+')         { ++p->p; }
        int uval = 0;
        if (!p_parse_int(p, &uval)) {
            p->err = 1; p->err_msg = "prosody value"; return 0;
        }
        int val = sign * uval;
        if (val < -127) val = -127; else if (val > 127) val = 127;
        if      (strcmp(key, "p") == 0) w->pitch_st = (int8_t)val;
        else if (strcmp(key, "r") == 0) w->rate_pct = (int8_t)val;
        /* unknown keys silently ignored — extensibility hatch. */
        p_skip_ws(p);
    }
    if (!p_expect_lit(p, "[")) return 0;
    /* Stress of the previous word's final syllable, for the fr-CA liaison
     * inheritance in parse_word_body. w is out->words[n_words-1]; the prior
     * word is [n_words-2]. Its last phoneme carries that syllable's stress. */
    int prev_last_stress = 0;
    if (out->n_words >= 2) {
        const fe_parsed_word_t *prev = &out->words[out->n_words - 2];
        if (prev->n_phonemes > 0)
            prev_last_stress = prev->phonemes[prev->n_phonemes - 1].syl_stress;
    }
    if (!parse_word_body(p, w, prev_last_stress)) return 0;
    if (!p_expect_lit(p, "]")) return 0;
    if (!p_expect_lit(p, ">")) return 0;
    return 1;
}

int fe_parse_tagged_output(const char *tagged, fe_parsed_t *out) {
    if (!tagged || !out) return -1;
    memset(out, 0, sizeof(*out));

    parser_t pp = {
        .p = tagged,
        .end = tagged + strlen(tagged),
        .err = 0,
        .err_msg = NULL,
    };
    parser_t *p = &pp;

    /* Tolerate leading whitespace + "%%". */
    p_skip_ws(p);
    p_match_lit(p, "%%");
    p_skip_ws(p);

    /* Outer loop over utterances. The FE emits one `#{...}` block per
     * phrase; multi-phrase inputs (e.g. "Hello, world." after a comma
     * boundary) come back as two consecutive blocks. We concatenate
     * all words / pauses into one fe_parsed_t for downstream
     * consumption; words from utterance K carry phrase_id=K. */
    int utt_count = 0;
    while (p->p < p->end) {
        int phrase_id_for_this_utt = utt_count;
        p_skip_ws(p);
        if (p->p >= p->end) break;
        if (p_match_lit(p, "%%")) { p_skip_ws(p); continue; }
        /* Single `%` is the inter-utterance separator the FE emits
         * between consecutive `{...}` blocks for ';' / multi-clause
         * boundaries (e.g. "Hello; world." → "{. ...} % {. ...} %%").
         * Without this, the parser stopped at the first `%` after
         * the first utt → only 1 utt processed for semicolon texts.
         * Verified by inspecting [fe_host] tagged output on edge_010. */
        if (p_peek(p) == '%') { p->p++; p_skip_ws(p); continue; }
        /* Utterance opener: first one is "#{", subsequent inter-utterance
         * separators are just "{". Be permissive. */
        if (!(p_match_lit(p, "#{") || p_match_lit(p, "{"))) {
            if (utt_count == 0) {
                p->err = 1; p->err_msg = "missing #{ opener"; goto fail;
            }
            break;
        }
        /* Capture per-utterance terminator marker. The FE emits the
         * boundary punctuation as the first char inside `{X` — `,`,
         * `.`, `?`, `!`, or `;`. We need this per-utterance because
         * pass-A/B in slot_ctx.c keys off it via local_10 to compute
         * sp[0] (sylInPhrase) and sp[3] (wordInPhrase). */
        {
            char term_marker = 0;
            p_skip_ws(p);
            char m = (char)p_peek(p);
            if (m == ',' || m == '.' || m == '?' || m == '!' || m == ';') {
                term_marker = m;
                p->p++;          /* consume it */
            }
            if (utt_count < (int)(sizeof(out->phrase_terms) /
                                  sizeof(out->phrase_terms[0]))) {
                out->phrase_terms[utt_count] = term_marker ? term_marker : '.';
                if (utt_count + 1 > out->n_phrase_terms)
                    out->n_phrase_terms = utt_count + 1;
            }
        }
        utt_count++;

        for (;;) {
            p_skip_ws(p);
            if (p_peek(p) == '}') { p->p++; break; }
            if (p->p >= p->end) { p->err = 1; p->err_msg = "unterminated #{"; goto fail; }

            /* "pau" literal before generic identifier parsing. */
            if (p->end - p->p >= 3 && p->p[0] == 'p' && p->p[1] == 'a' && p->p[2] == 'u') {
                p->p += 3;
                /* `pau(uN)` — USER pause from a `\!pN` embedded tag (emitted
                 * by build_inline_mixed_tagged). The `u` unit distinguishes it
                 * from the FE's structural `pau(pN)`, which is NOT rendered as
                 * silence; user pauses ARE, via phrase_lead_pause_ms. */
                if (p->end - p->p >= 2 && p->p[0] == '(' && p->p[1] == 'u') {
                    p->p += 2;
                    int dur = 0;
                    if (!p_parse_int(p, &dur)) { p->err = 1; p->err_msg = "user pause"; goto fail; }
                    if (!p_expect_lit(p, ")")) goto fail;
                    if (phrase_id_for_this_utt >= 0
                        && phrase_id_for_this_utt < FE_PARSE_MAX_PHRASES)
                        out->phrase_lead_pause_ms[phrase_id_for_this_utt] += dur;
                    continue;
                }
                int post = (out->n_words > 0);
                if (!parse_pau(p, out, /*post_word=*/(post != 0))) goto fail;
                continue;
            }
            if (p_peek(p) == '<') {
                p->p++;
                if (!parse_word(p, out)) goto fail;
                /* Tag the just-parsed word with the current utterance
                 * index. The engine emits one `#{...}` block per
                 * phrase, and engine-captured traces (prsl_slot,
                 * inner_scorer, ...) reset slot=0 at every phrase
                 * boundary. spfy_synth runs the slot-tree pipeline
                 * once per phrase_id and the audit scripts clip both
                 * sides to "first phrase only" — so preserving the
                 * FE's natural phrase splits keeps alignment. The
                 * SPFY_FE_HOST_PHRASE_MERGE=1 env var collapses
                 * everything into phrase 0 for callers that want
                 * a single uninterrupted audio output (no
                 * inter-phrase silence). */
                if (out->n_words > 0) {
                    int pid = getenv("SPFY_FE_HOST_PHRASE_MERGE")
                                ? 0 : phrase_id_for_this_utt;
                    out->words[out->n_words - 1].phrase_id = pid;
                }
                continue;
            }
            /* Skip stray punctuation permissively. */
            p->p++;
        }
        p_skip_ws(p);
    }
    apply_phoneme_refinement(out);
    return 0;

fail:
    fprintf(stderr, "[fe_parse] error at offset %td: %s\n",
            (ptrdiff_t)(p->p - tagged),
            p->err_msg ? p->err_msg : "(unknown)");
    fe_parsed_free(out);
    return -1;
}

/* ============================================================
 * Phoneme refinement (engine-side post-process emulation)
 *
 * The FE's drained ESPR text gives coarse phoneme names (`ih`, `t`,
 * `d`). The real engine's Festival utterance (captured via fe_tree)
 * has these refined to `ix`, `dx` per standard English post-lexical
 * rules. The refinement lives inside SWIttsUSel.dll (not accessible
 * here) but the rules can be derived empirically — see
 * memory/project_phoneme_refinement_rules_2026_05_12.md.
 *
 * Two rules:
 *   1. Unstressed `ih` → `ix` (vowel reduction)
 *   2. `t`/`d` in unstressed syllable-onset, between sonorant/vowel and
 *      vowel → `dx` (flapping)
 *
 * Applied here so downstream engine_phoneid_lookup sees the refined
 * names (ih=20 → ix=21, d=9 → dx=11, t=? → dx=11).
 *
 * Toggle off via SPFY_FE_HOST_NO_PHONEME_REFINE=1.
 * ============================================================ */

static int is_arpa_vowel(const char *p) {
    static const char *VOWELS[] = {
        "aa","ae","ah","ao","aw","ax","ay",
        "eh","er","ey",
        "ih","ix","iy",
        "ow","oy",
        "uh","uw",
        NULL
    };
    for (const char **v = VOWELS; *v; v++)
        if (strcmp(p, *v) == 0) return 1;
    return 0;
}
/* `is_arpa_sonorant_not_vowel` was the prev-context predicate for an
 * earlier (over-broad) version of R2 that included nasals as flap
 * triggers. Removed 2026-05-13 evening when the empirical rule
 * derivation showed engine excludes nasals (see R2 comment below). */

/* Refinement toggle. Default on for legacy callers; fe_host turns it off
 * once ESPR mode is enabled (the FE then emits reduced phones itself). */
static int s_refine_enabled = 1;

void fe_parse_set_refine(int enabled) { s_refine_enabled = enabled ? 1 : 0; }

void fe_parse_set_liaison_inherit(int enabled)
{
    s_liaison_inherit_stress = enabled ? 1 : 0;
}

static void apply_phoneme_refinement(fe_parsed_t *out) {
    if (!out || out->n_words == 0) return;
    if (!s_refine_enabled) return;
    if (getenv("SPFY_FE_HOST_NO_PHONEME_REFINE")) return;

    /* Pass 1: unstressed ih → ix AND unstressed ax → ix (onset-present).
     * Applied to ALL words regardless of prominence — engine refines
     * many prom=0 function words (e.g. nat_018 "is" prom=0 → ix).
     * Empirical false-positives (engine kept "it's"/"isn't"/"to" but
     * we refine) cost some slots but trying to filter them by a
     * cheap heuristic (prom, POS, length) made things WORSE overall
     * — the lexicon-specific decision needs lexicon data we don't
     * have. Living with the false-positives nets +13pp slot fidelity.
     * Empirical from nat_018: "recorded" syl1 r-ax → r-ix (onset r
     * present); "assurance" syl1 ax → ax stays (no onset). */
    int no_refine_enabled = (getenv("SPFY_FE_HOST_NO_LEXICAL_OVERRIDE") == NULL);
    for (int wi = 0; wi < out->n_words; wi++) {
        fe_parsed_word_t *w = &out->words[wi];
        /* Lowercase a copy of the word text for case-insensitive lookup
         * against the engine-derived (word, syl_idx) override table.
         * Engine names words lowercase in fe_tree (e.g. "to", "Hello"
         * becomes "hello"); our parser preserves casing from the tagged
         * FE stream, so we normalize on-demand here. */
        char wlow[64];
        size_t wl_n = strlen(w->text);
        if (wl_n >= sizeof(wlow)) wl_n = sizeof(wlow) - 1;
        for (size_t i = 0; i < wl_n; i++) wlow[i] = (char)tolower((unsigned char)w->text[i]);
        wlow[wl_n] = '\0';
        for (int pi = 0; pi < w->n_phonemes; pi++) {
            fe_parsed_phoneme_t *ph = &w->phonemes[pi];
            /* Stress gate: always fire on stress=0; for stress=2
             * (secondary stress), fire ONLY when the phoneme is a
             * singleton syllable (no onset, no coda) — i.e. its syl
             * contains exactly one phoneme. Empirical pivot
             * (2026-05-14, project_secondary_stress_singleton):
             * across the 4 stress=2 ih cases in the corpus, the
             * only engine-refined case (nat_049 "electronic" syl 0
             * [.2 ih]) is the singleton; the 3 kept cases all have
             * other phonemes in the syllable (nat_040 "inside"
             * [.2 ih n], nat_018 "being" [.2 ih ng], edge_008). */
            int singleton_syl = 0;
            if (ph->syl_stress == 2) {
                int prev_same = (pi > 0
                    && w->phonemes[pi - 1].syl_index == ph->syl_index);
                int next_same = (pi + 1 < w->n_phonemes
                    && w->phonemes[pi + 1].syl_index == ph->syl_index);
                singleton_syl = (!prev_same && !next_same);
            }
            if (ph->syl_stress != 0 && !singleton_syl) continue;
            /* Lexical override: engine keeps `ih`/`ax` unrefined in
             * specific (word, syl_idx) pairs that our R1/R3 rules
             * would otherwise over-refine to `ix`. Empirically built
             * from fe_tree captures across the 500-phrase oracle
             * corpus + a vocab sweep (spfy/tools/no_refine_codegen.py).
             * SPFY_FE_HOST_NO_LEXICAL_OVERRIDE=1 disables for A/B.
             *
             * Plus a small hardcoded list for high-frequency function
             * words the autogen sweep missed (or that fall outside the
             * 500-phrase training corpus). Discovered 2026-05-19 via
             * per-slot ctx_center attribution on the 226-phrase audit:
             * "this" syl 0 alone accounted for 92 of 94 `ix→ih`
             * cascade-source mismatches. */
            static const struct { const char *w; int s; } HARD_SKIP[] = {
                { "this", 0 },
                { NULL, 0 }
            };
            int hard_skip = 0;
            for (int hi = 0; HARD_SKIP[hi].w; ++hi) {
                if (HARD_SKIP[hi].s == ph->syl_index
                    && strcmp(HARD_SKIP[hi].w, wlow) == 0) {
                    hard_skip = 1; break;
                }
            }
            if (hard_skip) continue;
            if (no_refine_enabled
                && spfy_fe_should_skip_refinement(wlow, ph->syl_index)) {
                continue;
            }
            if (strcmp(ph->arpabet, "ih") == 0) {
                /* Exception: -ing endings (`ih` followed by `ng` in
                 * the same syllable) keep `ih`. Empirical: "working"
                 * syl 2 `k ih ng`, "raining" syl 2 `n ih ng` — engine
                 * keeps both as `ih`. */
                int next_is_ng_same_syl = (pi + 1 < w->n_phonemes
                    && w->phonemes[pi + 1].syl_index == ph->syl_index
                    && strcmp(w->phonemes[pi + 1].arpabet, "ng") == 0);
                if (next_is_ng_same_syl) continue;
                strncpy(ph->arpabet, "ix", sizeof(ph->arpabet) - 1);
                ph->arpabet[sizeof(ph->arpabet) - 1] = '\0';
                continue;
            }
            if (strcmp(ph->arpabet, "ax") == 0) {
                /* Onset present iff a phoneme of the same syl_index
                 * precedes ax in this word. Tried prom>0 gate (to
                 * avoid over-refining "the"/"to"/"of") — REGRESSED
                 * because engine refines ax in many prom=0 words too
                 * (just not those specific function words). Without
                 * lexicon access we can't predict which prom=0 words
                 * engine refines, so accept the false-positives. */
                int has_onset = (pi > 0
                    && w->phonemes[pi - 1].syl_index == ph->syl_index);
                if (has_onset) {
                    strncpy(ph->arpabet, "ix", sizeof(ph->arpabet) - 1);
                    ph->arpabet[sizeof(ph->arpabet) - 1] = '\0';
                }
            }
        }
    }

    /* Pass 2: flap rule (uses post-rule-1 names; runs after pass 1
     * so flap-context lookup sees ix where ih became ix).
     *
     * Predicate (derived 2026-05-13 evening from full-corpus
     * empirical pivot of 485 alveolar-stop slots vs engine's
     * fe_tree decisions; 97.7% agreement on the rule below):
     *   flap iff:
     *     phone in {t, d}
     *     AND curr_syl_stress == 0          (engine NEVER flaps cs>=1)
     *     AND prev in {VOWEL, 'r'}         (NOT n/m/ng/l — engine
     *                                         doesn't flap after nasals
     *                                         or 'l'; the 'twenty' nt
     *                                         keep cluster, "London" nd,
     *                                         etc.)
     *     AND next in {VOWEL, 'l', 'el'}   (NOT 'r' — onset cluster
     *                                         tr/dr blocks flap; NOT
     *                                         nasal — "wanted" nt-axn)
     *     AND NOT word-initial             (handled by prev_ph=NULL at
     *                                         word boundary, so the
     *                                         prev-class check fails)
     *
     * Prior rule used `prev_sonorant_or_vowel` (included nasals) and
     * `next_vowel` (excluded l/el). Net effect of the tightening:
     * stops over-flapping after nasals (twenty, holiday, calendar)
     * AND over-flapping into 'r' (no cases hit that direction here),
     * plus catches engine-flap into 'l' contexts.
     *
     * See project_flap_predicate_2026_05_13.md for the empirical
     * derivation (full pivot table, drilldown of outliers).
     *
     * Cross-word LOOK-AHEAD is applied (added 2026-05-13 evening,
     * after the tightened predicate landed): word-FINAL t/d looks at
     * the next word's first phoneme to detect intervocalic-across-
     * word-boundary cases the engine flaps ("road ahead", "att add").
     * Critically, look-BEHIND remains within-word only -- prev_ph is
     * reset at word boundaries -- because engine does NOT flap word-
     * initial t/d (e.g. "today" word-initial /t/ after vowel-final
     * prev word stays /t/, never /dx/). Word-initial t/d therefore
     * fails the predicate (prev_ph=NULL) regardless of prev word.
     * Pause boundary blocks cross-word lookahead. */
    fe_parsed_phoneme_t *prev_ph = NULL;
    for (int wi = 0; wi < out->n_words; wi++) {
        fe_parsed_word_t *w = &out->words[wi];
        prev_ph = NULL;   /* reset at word boundary — flap is within-word only */
        for (int pi = 0; pi < w->n_phonemes; pi++) {
            fe_parsed_phoneme_t *curr = &w->phonemes[pi];

            /* Look-ahead: same-word next, with cross-word fallback for
             * the word-final position (no pause after this word). */
            fe_parsed_phoneme_t *next = NULL;
            int xword_next = 0;
            if (pi + 1 < w->n_phonemes) {
                next = &w->phonemes[pi + 1];
            } else if (w->pause_after_ms == 0 && wi + 1 < out->n_words) {
                fe_parsed_word_t *nw = &out->words[wi + 1];
                /* Cross-word lookahead is bounded to the SAME phrase --
                 * comma/period boundaries that split into separate
                 * `#{...}` blocks (phrase_id increments) block the
                 * flap. Engine treats those as phrasal pause sites. */
                if (nw->n_phonemes > 0 && nw->phrase_id == w->phrase_id) {
                    next = &nw->phonemes[0];
                    xword_next = 1;
                }
            }

            /* Syllable-onset = first phoneme of its syl_index. */
            int is_onset = 0;
            if (pi == 0) is_onset = 1;
            else if (w->phonemes[pi - 1].syl_index != curr->syl_index)
                is_onset = 1;

            int is_t_or_d = (strcmp(curr->arpabet, "t") == 0
                             || strcmp(curr->arpabet, "d") == 0);
            int prev_v_or_r = prev_ph &&
                (is_arpa_vowel(prev_ph->arpabet)
                 || strcmp(prev_ph->arpabet, "r") == 0);
            int next_is_vowel = next && is_arpa_vowel(next->arpabet);
            int next_v_or_l = next &&
                (next_is_vowel
                 || strcmp(next->arpabet, "l") == 0
                 || strcmp(next->arpabet, "el") == 0);

            /* Cross-word resyllabification: when the t/d is word-final
             * before a VOWEL-initial next word in the SAME phrase, the
             * engine treats the flap as ONSET of the next word's first
             * syllable.
             *
             * Cross-word gating (empirical corpus pivot 2026-05-14,
             * project_xword_flap_2026_05_14): of 15 cross-word
             * t/d-before-V/l-initial-next cases, engine flaps 4/4 with
             * (next=vowel, prev=V/r) and keeps 11/11 with either
             * prev=consonant-cluster or next=l. Two-pronged rule:
             *   1. next_ph must be a VOWEL (not l/el) — engine never
             *      flaps cross-word into l-initial next-word
             *      ("would like", "airport leaves" stay /d/, /t/).
             *   2. stress gate BYPASSED cross-word — engine flaps
             *      regardless of next-word stress as long as prev=V/r
             *      ("att add" mp_050: next=ae stress=1; "permitted
             *      anywhere" nat_040: next=eh stress=1; both flap).
             * Within-word, the original next_v_or_l (including l/el)
             * + curr_stress==0 rule applies — these gates differ.
             *
             * Phrase boundary (comma -> separate `#{...}` block in the
             * tagged stream -> phrase_id increment) blocks cross-word
             * lookahead — engine treats those as phrasal pause sites. */
            int eff_stress     = xword_next ? 0 : curr->syl_stress;
            int eff_onset      = xword_next ? 1 : is_onset;
            int eff_next_match = xword_next ? next_is_vowel : next_v_or_l;
            if (is_t_or_d && eff_stress == 0 && eff_onset
                && prev_v_or_r && eff_next_match) {
                strncpy(curr->arpabet, "dx", sizeof(curr->arpabet) - 1);
                curr->arpabet[sizeof(curr->arpabet) - 1] = '\0';
            }

            prev_ph = curr;
        }
        /* Pause after this word breaks the cross-word context chain. */
        if (w->pause_after_ms != 0) prev_ph = NULL;
    }

    /* Pass 2.5: word-"to" vowel override.
     *
     * Empirical from full-corpus fe_tree pivot of 11 'to' occurrences
     * (project_vowel_reduction_2026_05_13): engine produces 3 distinct
     * vowels for "to" depending on next word:
     *   next=V (vowel-initial)              -> 'uw' (full form)
     *   next=`dh` (the word "the")          -> 'ix'
     *   next=other consonant                -> 'ax'
     * 100% coverage on the 11 cases (4 V, 3 dh, 4 other-C).
     *
     * The lexical-override `no_refine` table currently has ("to", 0)
     * to PREVENT R1/R3 from refining "to". That kept FE's per-context
     * 'to' lexicon entries (`t uw` / `dx ih` / `t ax` / `dx ax`)
     * unmodified — which matched engine in some contexts (next=other-C)
     * but mismatched in others (next=V or next=dh).
     *
     * Solution: keep the no_refine entry (so R1/R3 don't fire on "to"),
     * but apply this dedicated 3-way override after R2. We also force
     * the consonant to `t` (resp. `dx`) for cases where FE gave one but
     * the engine produced the other -- TODO if needed; current corpus
     * evidence doesn't show that mismatch.
     *
     * Cross-word lookahead obeys the same gates as R2: phrase_id match,
     * no pause boundary. */
    for (int wi = 0; wi < out->n_words; wi++) {
        fe_parsed_word_t *w = &out->words[wi];
        if (strcmp(w->text, "to") != 0
            && strcmp(w->text, "To") != 0) continue;
        if (w->n_phonemes < 2) continue;
        /* Vowel position: "to" is t-vowel; vowel is index 1. */
        fe_parsed_phoneme_t *vowel = &w->phonemes[1];

        /* Find next word's first phoneme (cross-word, same phrase, no
         * pause). If none reachable, leave alone. */
        const char *next_phone = NULL;
        if (w->pause_after_ms == 0 && wi + 1 < out->n_words) {
            fe_parsed_word_t *nw = &out->words[wi + 1];
            if (nw->phrase_id == w->phrase_id && nw->n_phonemes > 0) {
                next_phone = nw->phonemes[0].arpabet;
            }
        }
        if (!next_phone) continue;

        const char *new_vowel;
        if (is_arpa_vowel(next_phone))            new_vowel = "uw";
        else if (strcmp(next_phone, "dh") == 0)   new_vowel = "ix";
        else                                       new_vowel = "ax";

        strncpy(vowel->arpabet, new_vowel,
                sizeof(vowel->arpabet) - 1);
        vowel->arpabet[sizeof(vowel->arpabet) - 1] = '\0';
    }

    /* Pass 3 (R4): syllabic-L collapse.
     *
     * In syllables that end with `[ax|ih|ix] + l`, engine emits a
     * single `el` (syllabic L) for the pair.
     *
     * Gating (cross-corpus fe_tree evidence, 28 `el` emissions in
     * 225-phrase corpus + 3 NON-collapsed counter-examples — "pill"
     * monosyl stress=1, "silvio" syl0 stress=1 (word-initial),
     * "invisibility" syl3 stress=1 (word-internal)):
     *   collapse iff stress == 0
     *           OR  (stress == 1 AND syl is word-final AND word has >1 syllable).
     * The second branch covers "until" syl1 stress=1 word-final
     * (nat_019/030/037 STRUCTURE gap, verified empirically). The 3
     * counter-examples are all (stress=1, monosyllabic) or
     * (stress=1, not word-final) → not caught.
     *
     * SPFY_FE_HOST_NO_EL_COLLAPSE=1 disables for A/B. */
    if (!getenv("SPFY_FE_HOST_NO_EL_COLLAPSE")) {
        for (int wi = 0; wi < out->n_words; wi++) {
            fe_parsed_word_t *w = &out->words[wi];
            int syl_start = 0;
            while (syl_start < w->n_phonemes) {
                int sx = w->phonemes[syl_start].syl_index;
                int stress = w->phonemes[syl_start].syl_stress;
                int syl_end = syl_start + 1;
                while (syl_end < w->n_phonemes
                       && w->phonemes[syl_end].syl_index == sx) {
                    syl_end++;
                }
                int last = syl_end - 1;
                int word_final_syl = (sx == w->n_syllables - 1);
                int multi_syl = (w->n_syllables > 1);
                int can_collapse =
                    (stress == 0)
                    || (stress == 1 && word_final_syl && multi_syl);
                if (can_collapse && last > syl_start
                    && strcmp(w->phonemes[last].arpabet, "l") == 0) {
                    int vidx = last - 1;
                    const char *v = w->phonemes[vidx].arpabet;
                    if (strcmp(v, "ax") == 0
                        || strcmp(v, "ih") == 0
                        || strcmp(v, "ix") == 0) {
                        /* Rewrite `l` to `el`, drop the preceding vowel. */
                        strncpy(w->phonemes[last].arpabet, "el",
                                sizeof(w->phonemes[last].arpabet) - 1);
                        w->phonemes[last].arpabet[
                            sizeof(w->phonemes[last].arpabet) - 1] = '\0';
                        if (vidx + 1 < w->n_phonemes) {
                            memmove(&w->phonemes[vidx],
                                    &w->phonemes[vidx + 1],
                                    sizeof(fe_parsed_phoneme_t)
                                    * (size_t)(w->n_phonemes - vidx - 1));
                        }
                        w->n_phonemes--;
                        syl_end--;
                    }
                }
                syl_start = syl_end;
            }
        }
    }
}

void fe_clean_stream_inplace(char *s) {
    if (!s) return;
    char *r = s, *w = s;
    while (*r) {
        if (isspace((unsigned char)*r)) {
            const char *ws_start = r;
            while (*r && isspace((unsigned char)*r)) r++;
            ptrdiff_t ws_len = r - ws_start;
            int prev = (w > s) ? (unsigned char)*(w - 1) : 0;
            int next = (unsigned char)*r;
            if (ws_len >= 2 && isalnum(prev) && isalnum(next)) {
                /* chunk-seam artefact — drop entirely */
            } else {
                *w++ = ' ';
            }
        } else {
            *w++ = *r++;
        }
    }
    *w = '\0';
}

int fe_parsed_count_phonemes(const fe_parsed_t *out) {
    int n = 0;
    if (!out) return 0;
    for (int i = 0; i < out->n_words; i++) n += out->words[i].n_phonemes;
    return n;
}

void fe_parsed_free(fe_parsed_t *out) {
    if (!out) return;
    if (out->words) {
        for (int i = 0; i < out->n_words; i++) {
            free(out->words[i].phonemes);
        }
        free(out->words);
    }
    memset(out, 0, sizeof(*out));
}

/* Map a ToBI accent string to an emphasis level (0..3). */
static uint8_t accent_to_emphasis(const char *acc) {
    if (!acc || !*acc) return 0;
    /* Boundary tones alone (no asterisk) do not raise emphasis. A
     * pitch accent (H asterisk, L asterisk, L+H asterisk, ...) does. */
    if (strchr(acc, '*')) {
        /* Compound accents get +1. */
        if (strchr(acc, '+')) return 2;
        return 1;
    }
    return 0;
}

void fe_parsed_flatten_to_slots(const fe_parsed_t *parsed,
                                spfy_fe_slot_t *slots,
                                int slots_cap) {
    if (!parsed || !slots) return;
    int k = 0;
    for (int i = 0; i < parsed->n_words && k < slots_cap; i++) {
        const fe_parsed_word_t *w = &parsed->words[i];
        for (int j = 0; j < w->n_phonemes && k < slots_cap; j++) {
            const fe_parsed_phoneme_t *ph = &w->phonemes[j];
            spfy_fe_slot_t *s = &slots[k++];
            memset(s, 0, sizeof(*s));
            s->emphasis_level = accent_to_emphasis(ph->accent);
            /* ctx, sp, is_voiced and the durt / f0tr fields stay zero;
             * they require a phoneset crosswalk (ARPAbet to engine
             * HP-class IDs) that lives downstream. Prosody hints
             * (pitch/rate) are applied later in spfy_fe_synth_text
             * caller using the borrowed hints pointer on the utterance. */
        }
    }
}

/* phoneInSyl: the target-side row index into the VCF's phoneInSylCosts
 * matrix, whose row/column vocabulary is
 *
 *     0 UNDEF  1 WordInitial  2 SyllInitial  3 SyllMedial
 *     4 SyllFinal  5 WordFinal  6 SyllUnknown
 *
 * The rule below was recovered empirically from Jill's own voice data by
 * cross-referencing the per-unit phoneInSyl byte (disk +0x10, v100008)
 * against the independent _WORD_ / _SYL_ unit spans in the ckls chunk:
 * 3504/3504 units agree exactly, with an all-diagonal confusion matrix.
 * Note the precedence -- word edges outrank syllable edges, and SyllFinal
 * outranks SyllInitial, which is what a one-phone syllable resolves to.
 *
 * This replaces an earlier onset/nucleus/coda (0/1/2) encoding that did
 * not correspond to the matrix rows at all. It was inert on Tom, whose
 * PHONE_IN_SYL_MISMATCH_COST is 0 and who ships no phoneInSylCosts
 * matrix, but Jill weights this term at 0.3. */
static uint16_t classify_phone_in_syl(int phi, int n_phon_in_word,
                                      int pi_in_syl, int syl_n) {
    if (phi <= 0)                    return 1;   /* WordInitial */
    if (phi >= n_phon_in_word - 1)   return 5;   /* WordFinal   */
    if (pi_in_syl >= syl_n - 1)      return 4;   /* SyllFinal   */
    if (pi_in_syl <= 0)              return 2;   /* SyllInitial */
    return 3;                                    /* SyllMedial  */
}

/* Engine phone id for a symbol. Prefers the voice's own feat["name"]
 * order (correct for every language); falls back to the compiled-in
 * en-US table when the caller supplied none. */
static uint8_t engine_phone_id(const fe_phone_names_t *pn, const char *sym) {
    if (pn && pn->names) {
        for (uint32_t i = 0; i < pn->n; ++i) {
            if (pn->names[i] && strcmp(pn->names[i], sym) == 0)
                return (uint8_t)i;
        }
        return 0xff;
    }
    return spfy_engine_phoneid_lookup(sym);
}

int fe_parsed_to_full_slots(const fe_parsed_t       *parsed,
                            const spfy_phoneset_t   *ps,
                            const fe_phone_names_t  *pn,
                            spfy_fe_slot_t         **slots_out,
                            uint32_t                *n_slots_out) {
    if (!parsed || !slots_out || !n_slots_out) return -1;
    *slots_out = NULL; *n_slots_out = 0;

    uint32_t n_phons = (uint32_t)fe_parsed_count_phonemes(parsed);
    if (n_phons == 0) return 0;

    uint32_t n_slots = (n_phons + 2u) * 2u;
    spfy_fe_slot_t *slots = (spfy_fe_slot_t *)calloc(n_slots, sizeof *slots);
    if (!slots) return -1;

    /* Engine-faithful pau id (32 in en-US per the empirical table).
     * Only fall back to the VCF's silence_phone_id if the engine table
     * doesn't carry "pau" — should never happen in practice. */
    uint8_t pau_id = engine_phone_id(pn, "pau");
    if (pau_id == 0xff) {
        pau_id = (ps && ps->silence_phone_id != 0xff)
                   ? ps->silence_phone_id : 0u;
    }
    int32_t pau_side0 = (int32_t)pau_id * 2;
    int32_t pau_side1 = pau_side0 + 1;

    /* Leading pau pads (slots 0..1). */
    slots[0].ctx[2] = pau_side0;
    slots[1].ctx[2] = pau_side1;

    /* Walk parsed phonemes in linear order, tracking word/syl context. */
    uint32_t global_pi = 0;
    uint32_t syl_in_utt = 0;
    int prev_word = -1;
    int prev_syl_global_index = -1;
    int prev_syl_in_word = -1;

    for (int wi = 0; wi < parsed->n_words; wi++) {
        const fe_parsed_word_t *w = &parsed->words[wi];

        /* Index syllables within this word's phonemes once. */
        for (int phi = 0; phi < w->n_phonemes; phi++) {
            const fe_parsed_phoneme_t *ph = &w->phonemes[phi];

            /* Bump utterance-syllable counter on new syllable. */
            int this_syl_global = wi * 1000 + ph->syl_index;
            if (this_syl_global != prev_syl_global_index) {
                syl_in_utt++;
                prev_syl_global_index = this_syl_global;
                if (wi != prev_word) prev_syl_in_word = -1;
                prev_syl_in_word++;
                prev_word = wi;
            }

            /* Locate this phoneme's contiguous run within its syllable. */
            int syl_start = phi, syl_end = phi;
            while (syl_start > 0
                   && w->phonemes[syl_start - 1].syl_index == ph->syl_index)
                syl_start--;
            while (syl_end + 1 < w->n_phonemes
                   && w->phonemes[syl_end + 1].syl_index == ph->syl_index)
                syl_end++;
            int syl_n = syl_end - syl_start + 1;
            int pi_in_syl = phi - syl_start;
            uint16_t phon_in_syl = classify_phone_in_syl(
                phi, w->n_phonemes, pi_in_syl, syl_n);

            /* phone_id (for ctx[2]) comes from the engine's empirical
             * table; voiced still comes from the VCF since the engine
             * table doesn't carry that flag. Fall back to VCF id with a
             * stderr warning if the symbol isn't in the engine table. */
            uint8_t phone_id = 0, voiced = 0;
            uint8_t vid = ps ? spfy_phoneset_lookup(ps, ph->arpabet) : 0xff;
            if (vid != 0xff && vid < ps->n_phones) {
                voiced = ps->entries[vid].is_voiced;
            }
            uint8_t eid = engine_phone_id(pn, ph->arpabet);
            if (eid != 0xff) {
                phone_id = eid;
            } else if (vid != 0xff && vid < ps->n_phones) {
                phone_id = vid;
                fprintf(stderr,
                        "[fe_parse] warn: '%s' not in engine phone-id "
                        "table; falling back to VCF id=%u\n",
                        ph->arpabet, vid);
            }
            uint8_t emph = 0;
            if (ph->accent[0]) {
                if (strchr(ph->accent, '*')) {
                    emph = (strchr(ph->accent, '+')) ? 2u : 1u;
                }
            }

            uint32_t base = (global_pi + 1u) * 2u;
            for (int side = 0; side < 2; side++) {
                spfy_fe_slot_t *s = &slots[base + (uint32_t)side];
                s->ctx[2] = (int32_t)((uint32_t)phone_id * 2u + (uint32_t)side);
                s->is_voiced = voiced;
                s->emphasis_level = emph;
                /* SSML / Balabolka per-word prosody overrides flow from
                 * fe_parsed_word_t into every slot under this word.
                 * Downstream synth multiplies f0tr_mean by 2^(st/12)
                 * and divides durt_mean by (1 + rate_pct/100). */
                s->pitch_offset_st = w->pitch_st;
                s->rate_offset_pct = w->rate_pct;
                s->sp[0] = syl_in_utt;                   /* sylInPhrase */
                s->sp[1] = (uint32_t)ph->syl_stress;     /* sylType */
                s->sp[2] = (uint32_t)(prev_syl_in_word + 1); /* sylInWord */
                s->sp[3] = (uint32_t)(wi + 1);           /* wordInPhrase */
                s->sp[4] = phon_in_syl;                  /* phonInSyl */
            }

            global_pi++;
        }
    }

    /* Trailing pau pads. */
    uint32_t tail = (n_phons + 1u) * 2u;
    slots[tail + 0].ctx[2] = pau_side0;
    slots[tail + 1].ctx[2] = pau_side1;

    /* Same-side neighbour fill (i ± 2, i ± 4 with pau-encoded edge
     * sentinel matching slot side). Mirrors stage_spr.c. */
    for (uint32_t i = 0; i < n_slots; i++) {
        int32_t sentinel = (i & 1u) ? pau_side1 : pau_side0;
        slots[i].ctx[0] = (i >= 4)             ? slots[i - 4].ctx[2] : sentinel;
        slots[i].ctx[1] = (i >= 2)             ? slots[i - 2].ctx[2] : sentinel;
        slots[i].ctx[3] = (i + 2 < n_slots)    ? slots[i + 2].ctx[2] : sentinel;
        slots[i].ctx[4] = (i + 4 < n_slots)    ? slots[i + 4].ctx[2] : sentinel;
    }

    *slots_out = slots;
    *n_slots_out = n_slots;
    return 0;
}

void fe_parsed_debug_dump(const fe_parsed_t *p, FILE *out) {
    if (!p || !out) return;
    fprintf(out, "[fe_parse] pre_pause=%d post_pause=%d words=%d phonemes=%d\n",
            p->pause_before_ms, p->pause_after_ms,
            p->n_words, fe_parsed_count_phonemes(p));
    for (int i = 0; i < p->n_words; i++) {
        const fe_parsed_word_t *w = &p->words[i];
        fprintf(out, "  [%2d] '%s' (%d,%d) %s,%d  syls=%d phns=%d  pau_after=%d\n",
                i, w->text, w->char_start, w->char_len,
                w->pos, w->stress_level, w->n_syllables, w->n_phonemes,
                w->pause_after_ms);
        for (int j = 0; j < w->n_phonemes; j++) {
            const fe_parsed_phoneme_t *ph = &w->phonemes[j];
            fprintf(out, "        %2d: %-4s (p%d) syl=%d stress=%d acc='%s'\n",
                    j, ph->arpabet, ph->duration, ph->syl_index,
                    ph->syl_stress, ph->accent);
        }
    }
}
