#ifndef SPFY_SWITTSFE_REGISTRY_H
#define SPFY_SWITTSFE_REGISTRY_H

#include <stddef.h>

/* Registry of the SWIttsFe-<lang>.dll images embedded at build time.
 *
 * The table itself is generated by spfy/src/fe_host/CMakeLists.txt from
 * the SPFY_FE_LANGS list, so adding a language is a build-config change
 * rather than a code change. Each entry points at the bytes emitted by
 * embed_dll.py.
 *
 * `size` is a POINTER because embed_dll.py emits the size as a const
 * object (`const size_t prefix_size = sizeof(prefix_data);`), which is
 * not a constant expression and so cannot initialise a struct field
 * directly. */
typedef struct {
    const char          *lang;   /* e.g. "en-US", "fr-CA", "es-MX" */
    const unsigned char *data;
    const size_t        *size;
} spfy_fe_dll_entry_t;

extern const spfy_fe_dll_entry_t spfy_fe_dlls[];
extern const size_t              spfy_fe_n_dlls;

/* Look up an embedded FE image by VCF language tag (case-insensitive).
 * Returns NULL when the language was not built in. */
const spfy_fe_dll_entry_t *spfy_fe_dll_for_lang(const char *lang);

#endif
