/* spfy_cart_replay -- M1 acceptance harness.
 *
 * Loads a voice's f0tr and durt CART trees, then replays a Frida-captured
 * cart_walks JSONL trace through our walker, asserting that each walk
 * reaches the same leaf the engine reached.
 *
 *   spfy_cart_replay <voice.vin> <walks.jsonl>
 *
 * The walks.jsonl is generated by:
 *   python spfy/test/oracle/run_frida_capture.py --hook cart_walks ...
 *
 * For each captured walk, we build a {q_type -> value} map from the
 * recorded questions and traverse our tree using a callback that looks
 * up by q_type. If we land on the same leaf (mean & var match exactly),
 * the walk passes. M1 DoD = 100% pass over the corpus.
 *
 * NB: durt has 47 trees (one per phone). The walks JSONL records the
 * engine's phone_idx (from the durt walker's edx arg, see cart_walks_hook.js)
 * so we do EXACT-TREE match. If phone_idx is missing in the trace, we
 * fall back to probing all 47 trees and accepting any that reproduces
 * the leaf with no missing q_types -- this preserves backward
 * compatibility with traces captured before the hook was upgraded.
 */

#include <spfy/spfy.h>
#include "../voice/voice.h"
#include "../cart/cart.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Tiny JSON walker for one JSONL line.
 * Walks-format is regular: {"type":"cart_walk","n":N,"tree":"durt"|"f0tr",
 *   "slot":S,"questions":[{"q_type":T,"value":V},...],"leaf_mean":F,"leaf_var":F}
 * We don't ship a JSON dep; this scanner is field-extractor only. */

static const char *find_key(const char *buf, const char *end, const char *key)
{
    size_t kn = strlen(key);
    char needle[64];
    if (kn + 3 >= sizeof needle) return NULL;
    needle[0] = '"';
    memcpy(needle + 1, key, kn);
    needle[kn + 1] = '"';
    needle[kn + 2] = ':';
    needle[kn + 3] = '\0';
    for (const char *p = buf; p + kn + 3 <= end; ++p) {
        if (memcmp(p, needle, kn + 3) == 0) return p + kn + 3;
    }
    return NULL;
}

static int parse_int_at(const char *p, const char *end, long *out)
{
    while (p < end && (*p == ' ' || *p == '\t')) ++p;
    char *e = NULL;
    long v = strtol(p, &e, 10);
    if (e == p) return -1;
    if (e > end) return -1;
    *out = v;
    return 0;
}

static int parse_double_at(const char *p, const char *end, double *out)
{
    while (p < end && (*p == ' ' || *p == '\t')) ++p;
    char *e = NULL;
    double v = strtod(p, &e);
    if (e == p) return -1;
    if (e > end) return -1;
    *out = v;
    return 0;
}

static int parse_str_at(const char *p, const char *end, char *out, size_t outn)
{
    while (p < end && (*p == ' ' || *p == '\t')) ++p;
    if (p >= end || *p != '"') return -1;
    ++p;
    size_t i = 0;
    while (p < end && *p != '"' && i + 1 < outn) {
        out[i++] = *p++;
    }
    out[i] = '\0';
    return p < end ? 0 : -1;
}

/* Replay context: cached q_type -> value lookup from the captured walk. */
typedef struct {
    int32_t  by_type[16];      /* q_type 1..9; -1 = unobserved */
    int      missed_qtype;     /* set if walker asked a q_type not captured */
} replay_ctx;

static int32_t replay_feat(uint32_t q_type, void *user)
{
    replay_ctx *r = (replay_ctx *)user;
    if (q_type >= 16 || r->by_type[q_type] < 0) {
        r->missed_qtype = (int)q_type;
        return 0;       /* arbitrary; the divergence will show up in leaf */
    }
    return r->by_type[q_type];
}

static int floats_equal(float a, float b)
{
    union { float f; uint32_t u; } ua, ub;
    ua.f = a; ub.f = b;
    return ua.u == ub.u;
}

typedef struct {
    long     n_walks;
    long     n_pass;
    long     n_unmatched_durt;     /* no durt tree reproduced this leaf */
    long     n_leaf_mismatch;      /* walked but landed on wrong leaf */
    long     n_qtype_missing;      /* walker asked q_type not in capture */
    long     n_f0tr_pass;
    long     n_f0tr_fail;
    long     n_durt_exact_pass;    /* exact-tree match (phone_idx in trace) */
    long     n_durt_probe_pass;    /* legacy probe-all-trees match */
} stats_t;

static int replay_one_walk(const spfy_cart_t *f0tr,
                           const spfy_cart_t *durt,
                           const char *line, size_t n,
                           stats_t *st)
{
    const char *end = line + n;

    char tree[16] = {0};
    {
        const char *p = find_key(line, end, "tree");
        if (!p) return 0;
        if (parse_str_at(p, end, tree, sizeof tree) != 0) return 0;
    }

    double leaf_mean = 0, leaf_var = 0;
    {
        const char *p = find_key(line, end, "leaf_mean");
        if (!p) return 0;
        if (parse_double_at(p, end, &leaf_mean) != 0) return 0;
        p = find_key(line, end, "leaf_var");
        if (!p) return 0;
        if (parse_double_at(p, end, &leaf_var) != 0) return 0;
    }

    /* Build q_type -> value map by scanning all "q_type": ... "value": ...
     * pairs. Multiple occurrences of the same q_type override (last wins).
     * The CART semantics make repeats deterministic: same q_type asked
     * mid-walk must yield same value. */
    replay_ctx ctx;
    for (size_t i = 0; i < sizeof ctx.by_type / sizeof ctx.by_type[0]; ++i)
        ctx.by_type[i] = -1;
    ctx.missed_qtype = -1;

    const char *p = line;
    for (;;) {
        const char *qt = find_key(p, end, "q_type");
        if (!qt) break;
        long t = 0;
        if (parse_int_at(qt, end, &t) != 0) break;
        const char *vp = find_key(qt, end, "value");
        if (!vp) break;
        long v = 0;
        if (parse_int_at(vp, end, &v) != 0) break;
        if (t >= 0 && t < 16) ctx.by_type[t] = (int32_t)v;
        p = vp + 1;     /* advance past this match */
    }

    st->n_walks++;
    float want_mean = (float)leaf_mean;
    float want_var  = (float)leaf_var;

    if (strcmp(tree, "f0tr") == 0) {
        float got_mean = 0, got_var = 0;
        int rc = spfy_cart_traverse(f0tr, 0, replay_feat, &ctx,
                                    &got_mean, &got_var);
        int ok = rc == SPFY_OK
              && floats_equal(got_mean, want_mean)
              && floats_equal(got_var,  want_var);
        if (ok) { st->n_pass++; st->n_f0tr_pass++; }
        else    { st->n_leaf_mismatch++; st->n_f0tr_fail++; }
        if (ctx.missed_qtype >= 0) st->n_qtype_missing++;
        return ok;
    }
    if (strcmp(tree, "durt") == 0) {
        /* Prefer exact-tree match using captured phone_idx. Fall back to
         * probe-all-trees only if the trace is from an older hook that
         * didn't capture phone_idx. */
        long phone_idx = -1;
        const char *pi = find_key(line, end, "phone_idx");
        if (pi) parse_int_at(pi, end, &phone_idx);

        if (phone_idx >= 0 && (uint32_t)phone_idx < durt->n_trees) {
            float got_mean = 0, got_var = 0;
            int rc = spfy_cart_traverse(durt, (uint32_t)phone_idx,
                                        replay_feat, &ctx,
                                        &got_mean, &got_var);
            int ok = rc == SPFY_OK
                  && floats_equal(got_mean, want_mean)
                  && floats_equal(got_var,  want_var);
            if (ok) { st->n_pass++; st->n_durt_exact_pass++; }
            else    { st->n_leaf_mismatch++; }
            if (ctx.missed_qtype >= 0) st->n_qtype_missing++;
            return ok;
        }

        /* Legacy: probe all 47 trees, accept any consistent match. */
        int matched = 0;
        for (uint32_t ti = 0; ti < durt->n_trees && !matched; ++ti) {
            replay_ctx local = ctx;
            local.missed_qtype = -1;
            float got_mean = 0, got_var = 0;
            int rc = spfy_cart_traverse(durt, ti, replay_feat, &local,
                                        &got_mean, &got_var);
            if (rc != SPFY_OK) continue;
            if (local.missed_qtype >= 0) continue;
            if (floats_equal(got_mean, want_mean) &&
                floats_equal(got_var,  want_var)) {
                matched = 1;
            }
        }
        if (matched) { st->n_pass++; st->n_durt_probe_pass++; }
        else         st->n_unmatched_durt++;
        return matched;
    }
    return 0;
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <voice.vin> <walks.jsonl>\n", argv[0]);
        return 2;
    }

    /* Load just the VIN -- we don't need VDB or VCF for CART replay. */
    spfy_vin_t vin = {0};
    int rc = spfy_vin_load(argv[1], &vin);
    if (rc != SPFY_OK) {
        fprintf(stderr, "vin_load: %s\n", spfy_strerror(rc));
        return 1;
    }
    spfy_cart_t f0tr = {0}, durt = {0};
    rc = spfy_cart_load_f0tr(&vin, &f0tr);
    if (rc != SPFY_OK) {
        fprintf(stderr, "f0tr_load: %s\n", spfy_strerror(rc));
        return 1;
    }
    rc = spfy_cart_load_durt(&vin, &durt);
    if (rc != SPFY_OK) {
        fprintf(stderr, "durt_load: %s\n", spfy_strerror(rc));
        return 1;
    }

    fprintf(stdout, "loaded f0tr: %u trees, %u questions\n",
            f0tr.n_trees, f0tr.n_ques);
    fprintf(stdout, "loaded durt: %u trees, %u questions\n",
            durt.n_trees, durt.n_ques);

    FILE *fp = fopen(argv[2], "rb");
    if (!fp) { fprintf(stderr, "open %s\n", argv[2]); return 1; }

    char buf[16384];
    stats_t st = {0};
    while (fgets(buf, sizeof buf, fp)) {
        size_t n = strlen(buf);
        while (n > 0 && (buf[n-1] == '\n' || buf[n-1] == '\r')) buf[--n] = 0;
        if (n == 0) continue;
        replay_one_walk(&f0tr, &durt, buf, n, &st);
    }
    fclose(fp);

    fprintf(stdout, "\nwalks            : %ld\n", st.n_walks);
    fprintf(stdout, "passed           : %ld\n", st.n_pass);
    fprintf(stdout, "  f0tr pass/fail : %ld / %ld\n",
            st.n_f0tr_pass, st.n_f0tr_fail);
    fprintf(stdout, "  durt exact     : %ld  (phone_idx in trace -> exact tree match)\n",
            st.n_durt_exact_pass);
    fprintf(stdout, "  durt probe     : %ld  (legacy any-tree probe)\n",
            st.n_durt_probe_pass);
    fprintf(stdout, "leaf mismatch    : %ld\n", st.n_leaf_mismatch);
    fprintf(stdout, "no durt match    : %ld\n", st.n_unmatched_durt);
    fprintf(stdout, "q_type missing   : %ld (walker asked feature not in capture)\n",
            st.n_qtype_missing);

    spfy_cart_free(&f0tr);
    spfy_cart_free(&durt);
    spfy_vin_free(&vin);
    return st.n_pass == st.n_walks ? 0 : 1;
}
