/* engine_phoneid.h — generated by spfy/tools/engine_phoneid_to_c.py.
 * DO NOT EDIT. Re-run codegen if en_us_engine_phone_ids.csv changes.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef SPFY_ENGINE_PHONEID_H
#define SPFY_ENGINE_PHONEID_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Returns the engine's internal phone-id for an ARPAbet symbol, or
 * 0xff if the symbol is not present in the empirical table.
 * Lookup is case-sensitive and bsearch (O(log n)). */
uint8_t spfy_engine_phoneid_lookup(const char *arpabet);

/* Number of distinct ARPAbet symbols in the table. */
extern const uint32_t spfy_engine_phoneid_count;

#ifdef __cplusplus
}}
#endif

#endif /* SPFY_ENGINE_PHONEID_H */
