/* engine_phoneid.c — generated by spfy/tools/engine_phoneid_to_c.py.
 * DO NOT EDIT. Re-run codegen if en_us_engine_phone_ids.csv changes.
 *
 * Source: en_us_engine_phone_ids.csv (45 rows, 2301 total observations)
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */
#include "engine_phoneid.h"

#include <stdlib.h>
#include <string.h>

typedef struct {
    const char *name;
    uint8_t     id;
} engine_phone_t;

/* Sorted by name (ASCII). bsearch invariant. */
static const engine_phone_t TABLE[] = {
    { "aa",   0 },
    { "ae",   1 },
    { "ah",   2 },
    { "ao",   3 },
    { "aw",   4 },
    { "ax",   5 },
    { "ay",   6 },
    { "b",   7 },
    { "ch",   8 },
    { "d",   9 },
    { "dh",  10 },
    { "dx",  11 },
    { "eh",  12 },
    { "el",  13 },
    { "en",  14 },
    { "er",  15 },
    { "ey",  16 },
    { "f",  17 },
    { "g",  18 },
    { "hh",  19 },
    { "ih",  20 },
    { "ix",  21 },
    { "iy",  22 },
    { "jh",  23 },
    { "k",  24 },
    { "l",  25 },
    { "m",  26 },
    { "n",  27 },
    { "ng",  28 },
    { "ow",  29 },
    { "oy",  30 },
    { "p",  31 },
    { "pau",  32 },
    { "r",  33 },
    { "s",  34 },
    { "sh",  35 },
    { "t",  36 },
    { "th",  37 },
    { "uh",  38 },
    { "uw",  39 },
    { "v",  40 },
    { "w",  41 },
    { "y",  43 },
    { "z",  44 },
    { "zh",  45 },
};

const uint32_t spfy_engine_phoneid_count =
    sizeof(TABLE) / sizeof(TABLE[0]);

static int cmp_name(const void *key, const void *elem) {
    const char *k = (const char *)key;
    const engine_phone_t *e = (const engine_phone_t *)elem;
    return strcmp(k, e->name);
}

uint8_t spfy_engine_phoneid_lookup(const char *arpabet) {
    if (!arpabet) return 0xff;
    const engine_phone_t *r = (const engine_phone_t *)bsearch(
        arpabet, TABLE, spfy_engine_phoneid_count,
        sizeof(TABLE[0]), cmp_name);
    return r ? r->id : 0xff;
}
