/* AUTO-GENERATED by spfy/tools/capture_pos_disambig.py — do not edit.
 * Three-tier POS lookup captured from the DLL FE (SWIttsFe-en-US.dll).
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef SPFY_POS_CONTEXT_H
#define SPFY_POS_CONTEXT_H

#include "baked_pos.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Returns the engine's empirically-observed POS for a word in the
 * given context (`prev_word` and `next_word` may be NULL; pass the
 * sentinel "^"/"$" strings for BOS/EOS). Falls through:
 *   triple → bigram → unigram → POS_UNKNOWN.
 * Returns POS_UNKNOWN only when the word was never seen during capture. */
spfy_pos_class_t spfy_pos_context_lookup(const char *word_lower,
                                          const char *prev_word_lower,
                                          const char *next_word_lower);

#ifdef __cplusplus
}
#endif

#endif
