/* AUTO-GENERATED by spfy/tools/fe_dict_to_c.py - DO NOT EDIT. */
/* Source: fe_dict.jsonl (driven by spfy_dumpwav --g2p over the
 * registry-A/B word lists). */
#ifndef SPFY_FE_BAKED_DICT_H
#define SPFY_FE_BAKED_DICT_H

#include <stddef.h>
#include <stdint.h>

/* Lookup a word in the baked dictionary. */
int spfy_fe_baked_dict_lookup(const char *word_lc, size_t word_len,
                              const uint16_t **out_phons,
                              const uint8_t  **out_stress,
                              size_t *out_n);

#endif
