/* AUTO-GENERATED by spfy/tools/fe_dict_to_c.py — DO NOT EDIT. */
/* Source: c:/tmp/fe_dict.jsonl (driven by spfy_dumpwav --g2p
 * over the registry-A/B word lists). Faithful to the engine
 * for words present; OOC words still fall through to heuristic G2P. */
#ifndef SPFY_FE_BAKED_DICT_H
#define SPFY_FE_BAKED_DICT_H

#include <stddef.h>
#include <stdint.h>

/* Lookup a word in the baked dictionary.
 * Input: lowercase ASCII word + its byte length.
 * On hit: *out_phons -> u16 vocab IDs, *out_stress -> u8 stress
 *         (0/1/2 ARPAbet stress markers, parallel to out_phons),
 *         *out_n is the array length, returns 1.
 *         out_stress may be NULL if caller doesn't want stress.
 * On miss: returns 0 (out_* untouched). */
int spfy_fe_baked_dict_lookup(const char *word_lc, size_t word_len,
                              const uint16_t **out_phons,
                              const uint8_t  **out_stress,
                              size_t *out_n);

#endif
