/*
 * host/loader.h — minimal in-memory PE32 loader for SWIttsFe-en-US.dll
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026
 *
 * Written from the PE/COFF spec (Microsoft "PE Format" docs, public).
 * No code copied from third-party loaders.
 *
 * Loads a 32-bit Windows DLL from an in-memory byte buffer. The DLL bytes
 * are expected to be baked into the host binary as a C resource (see
 * src/fe_host/swittsfe_data.c, generated by xxd / CMake file(READ HEX)).
 *
 * Target platform for Task 2 deliverable: Windows x86 (32-bit host
 * process linked against MSVCR* / kernel32). The DLL is 32-bit x86 PE,
 * so the host must be 32-bit too.
 *
 * Cross-platform (Linux/macOS) is a future stretch goal — see notes in
 * host_notes.md. The interface here doesn't bake in any Windows types.
 */

#ifndef HOST_LOADER_H
#define HOST_LOADER_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct host_dll host_dll_t;

/* Import resolver callback. The loader calls this for each (dll, name)
 * tuple in the import directory; the caller (typically host/imports.c)
 * returns a function pointer that satisfies the import, or NULL on
 * failure.
 *
 * `dll` is the lowercased imported DLL name (e.g. "kernel32.dll").
 * `name_or_ordinal` is the imported symbol name, or NULL if `ordinal`
 *   is non-zero (PE supports both modes; SWIttsFe imports by name only).
 * `ordinal` is the imported ordinal (0 if name-based import).
 *
 * Return: function pointer that will be patched into the IAT. NULL
 * aborts the load.
 */
typedef void *(*host_import_resolver)(const char *dll,
                                      const char *name_or_ordinal,
                                      uint16_t ordinal,
                                      void *user);

/* Load a DLL from a memory buffer. Returns NULL on failure (use
 * host_dll_last_error to retrieve a short description). */
host_dll_t *host_dll_load(const void *dll_bytes,
                          size_t dll_size,
                          host_import_resolver resolve,
                          void *resolver_user);

/* Resolve an export by name. Returns NULL if the symbol is not
 * exported. */
void *host_dll_get_proc(host_dll_t *dll, const char *name);

/* Unload — calls DllMain(DLL_PROCESS_DETACH), then releases all mapped
 * pages. */
void host_dll_free(host_dll_t *dll);

/* Last-error string for the most recent failed host_dll_load (or
 * host_dll_get_proc). Thread-local in a real impl; the Task 2
 * implementation uses a single static buffer — fine for single-threaded
 * test/CLI use. */
const char *host_dll_last_error(void);

/* For debugging — return the base address the DLL was actually loaded
 * at (after relocation). */
const void *host_dll_image_base(host_dll_t *dll);

#ifdef __cplusplus
}
#endif

#endif /* HOST_LOADER_H */
