/* AUTOGENERATED by spfy/tools/voicing_codegen.py — do not edit. */
#include "tom_voicing.h"

const uint32_t spfy_tom_voicing[] = {
    1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u,
    1u, 1u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 1u, 1u, 1u, 1u, 1u, 1u,
    1u, 1u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u,
    1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 0u, 0u,
    1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u,
    1u, 1u, 0u, 0u, 0u, 0u, 1u, 1u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 1u, 1u, 1u, 1u,
    0u, 0u, 1u, 1u, 1u, 1u, 1u, 1u, 0u, 0u,
    0u, 0u,
};

const uint32_t spfy_tom_voicing_n = 92u;
