#ifndef SPFY_TOM_VOICING_H
#define SPFY_TOM_VOICING_H

#include <stdint.h>

/* Engine's per-hp-class voicing table for Tom (voice+0x5fc).
 *
 * Used by spfy_hp_innerscorer to gate the F0 cost component:
 *   if (voicing_table[hp_class] == 0) -> skip F0 entirely (no miss=5,
 *                                       no delta cost)
 *   else                              -> apply f0_start==0 miss or
 *                                       delta-based cost.
 *
 * Generated by spfy/tools/voicing_codegen.py from a Frida-captured
 * inner_scorer.join_consts.voice_5fc_per_uid.by_hp_class field. */
extern const uint32_t spfy_tom_voicing[];
extern const uint32_t spfy_tom_voicing_n;

#endif
